import { Player, MatchFixture, MatchEvent, FormationConfig, ScoutingReport } from './types';

export const PEDDIE_ROSTER_2026_2027: Player[] = [
  {
    id: 'p-1',
    number: 1,
    name: "Liam O'Connor",
    classYear: 'Senior',
    gradYear: 2027,
    position: 'GK',
    overallRating: 90,
    height: "6'2\"",
    weight: '185 lbs',
    hometown: 'Princeton, NJ',
    minutesPlayed: 1080,
    matchesPlayed: 12,
    goals: 0,
    assists: 1,
    expectedGoals: 0,
    expectedAssists: 0.15,
    passCompletionPct: 84.5,
    tackleSuccessPct: 92.0,
    topSpeedKmh: 28.4,
    distanceCoveredKm: 58.2,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Sweeper keeper box aerial command', notes: 'Collected 5 high crosses, initiated 80m counter with distribution' },
      { match: 'vs Lawrenceville', opponent: 'Lawrenceville', grade: '+', assignment: 'Penalty shootout & 1v1 denial', notes: 'Saved 89th minute breakaway 1v1 shot' }
    ],
    recruitmentNotes: 'Division 1 Ivy League / Patriot League prospect. Elite reflexes, 70-yard aerial kicking range.'
  },
  {
    id: 'p-4',
    number: 4,
    name: 'Julian Vance',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CB',
    isCaptain: true,
    overallRating: 93,
    height: "6'1\"",
    weight: '178 lbs',
    hometown: 'Hightstown, NJ',
    minutesPlayed: 1120,
    matchesPlayed: 13,
    goals: 3,
    assists: 2,
    expectedGoals: 2.1,
    expectedAssists: 1.4,
    passCompletionPct: 91.2,
    tackleSuccessPct: 88.6,
    topSpeedKmh: 33.5,
    distanceCoveredKm: 124.6,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Neutralize target striker #9 in aerial duels', notes: 'Won 11 of 12 aerial duels, scored 34th minute header off corner' },
      { match: 'vs Hun School', opponent: 'Hun', grade: '+', assignment: 'High defensive line offside trap leadership', notes: 'Caught opponent offside 6 times' }
    ],
    recruitmentNotes: 'ALL-MAPL 1st Team selection. Exceptional vocal leader, ball-playing center back with elite verticality.'
  },
  {
    id: 'p-5',
    number: 5,
    name: 'Lucas Davies',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CB',
    overallRating: 87,
    height: "6'0\"",
    weight: '174 lbs',
    hometown: 'Cranbury, NJ',
    minutesPlayed: 980,
    matchesPlayed: 12,
    goals: 1,
    assists: 1,
    expectedGoals: 0.8,
    expectedAssists: 0.9,
    passCompletionPct: 88.0,
    tackleSuccessPct: 84.2,
    topSpeedKmh: 32.8,
    distanceCoveredKm: 118.4,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Covering depth behind #4 Vance', notes: 'Made 4 crucial last-man sliding interceptions' }
    ],
    recruitmentNotes: 'Dominant slide tackler, composed left-foot passing range out from the back.'
  },
  {
    id: 'p-3',
    number: 3,
    name: 'Alex Rivera',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'LB',
    overallRating: 88,
    height: "5'10\"",
    weight: '162 lbs',
    hometown: 'Newtown, PA',
    minutesPlayed: 1040,
    matchesPlayed: 13,
    goals: 2,
    assists: 6,
    expectedGoals: 1.2,
    expectedAssists: 5.4,
    passCompletionPct: 85.3,
    tackleSuccessPct: 81.0,
    topSpeedKmh: 34.1,
    distanceCoveredKm: 138.9,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Overlapping flank progression and whip crosses', notes: 'Delivered cross leading to game-winner' }
    ],
    recruitmentNotes: 'Modern dynamic wingback with tireless stamina and pin-point curling delivery.'
  },
  {
    id: 'p-2',
    number: 2,
    name: 'Ethan Zhang',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'RB',
    overallRating: 86,
    height: "5'9\"",
    weight: '158 lbs',
    hometown: 'West Windsor, NJ',
    minutesPlayed: 890,
    matchesPlayed: 11,
    goals: 1,
    assists: 4,
    expectedGoals: 0.9,
    expectedAssists: 3.8,
    passCompletionPct: 86.1,
    tackleSuccessPct: 79.4,
    topSpeedKmh: 34.6,
    distanceCoveredKm: 119.5,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Contain explosive opposing winger', notes: 'Zero fouls conceded, locked down right flank' }
    ],
    recruitmentNotes: 'Fastest 10m sprint in the varsity squad. High ceiling underclassman prospect.'
  },
  {
    id: 'p-6',
    number: 6,
    name: 'Christian Bell',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CDM',
    overallRating: 89,
    height: "5'11\"",
    weight: '168 lbs',
    hometown: 'Red Bank, NJ',
    minutesPlayed: 1090,
    matchesPlayed: 13,
    goals: 2,
    assists: 4,
    expectedGoals: 1.4,
    expectedAssists: 4.1,
    passCompletionPct: 92.4,
    tackleSuccessPct: 86.8,
    topSpeedKmh: 32.2,
    distanceCoveredKm: 146.2,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Pivot press-breaker and central midfield shield', notes: 'Broached 8 high-press sequences without losing possession' }
    ],
    recruitmentNotes: 'Busquets-style single pivot. Reads game 2 moves ahead, 360-degree vision.'
  },
  {
    id: 'p-8',
    number: 8,
    name: 'Mateo Rossi',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CM',
    isCaptain: true,
    overallRating: 94,
    height: "5'11\"",
    weight: '165 lbs',
    hometown: 'East Windsor, NJ',
    minutesPlayed: 1140,
    matchesPlayed: 13,
    goals: 7,
    assists: 11,
    expectedGoals: 6.2,
    expectedAssists: 10.8,
    passCompletionPct: 93.8,
    tackleSuccessPct: 82.5,
    topSpeedKmh: 33.1,
    distanceCoveredKm: 152.4,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Control tempo and unlock low defensive block', notes: 'Assisted 2 goals, completed 88 passes at 95% clip' },
      { match: 'vs Hill School', opponent: 'Hill', grade: '+', assignment: 'Direct free kick and set-piece orchestrator', notes: 'Scored 28-yard direct curler into top right corner' }
    ],
    recruitmentNotes: 'ALL-MAPL #1 Midfielder. Top 5 ranking in New Jersey Prep. Metronomic tempo setter, elite free kick accuracy.'
  },
  {
    id: 'p-10',
    number: 10,
    name: 'Leo Sterling',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CAM',
    overallRating: 91,
    height: "5'10\"",
    weight: '160 lbs',
    hometown: 'Moorestown, NJ',
    minutesPlayed: 990,
    matchesPlayed: 12,
    goals: 8,
    assists: 7,
    expectedGoals: 7.4,
    expectedAssists: 6.9,
    passCompletionPct: 87.2,
    tackleSuccessPct: 71.0,
    topSpeedKmh: 33.8,
    distanceCoveredKm: 134.1,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Find pockets between midfield and back line', notes: 'Dribbled past 4 defenders, drew penalty' }
    ],
    recruitmentNotes: 'Creative maestro. Devastating close control in tight half-spaces, lethal trivela passes.'
  },
  {
    id: 'p-11',
    number: 11,
    name: 'Xavier Dupont',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'LW',
    overallRating: 92,
    height: "6'0\"",
    weight: '170 lbs',
    hometown: 'Cherry Hill, NJ',
    minutesPlayed: 1020,
    matchesPlayed: 13,
    goals: 9,
    assists: 8,
    expectedGoals: 8.5,
    expectedAssists: 7.2,
    passCompletionPct: 83.4,
    tackleSuccessPct: 69.2,
    topSpeedKmh: 35.4,
    distanceCoveredKm: 136.8,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Isolate right fullback 1v1 and cut inside to shoot', notes: 'Scored curling shot to open scoring 18th minute' }
    ],
    recruitmentNotes: 'Elite speed and ball-striking. High-volume chance creator and direct goal threat.'
  },
  {
    id: 'p-7',
    number: 7,
    name: 'Tyler Brooks',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'RW',
    overallRating: 88,
    height: "5'9\"",
    weight: '155 lbs',
    hometown: 'Pennington, NJ',
    minutesPlayed: 940,
    matchesPlayed: 12,
    goals: 6,
    assists: 5,
    expectedGoals: 5.8,
    expectedAssists: 4.6,
    passCompletionPct: 82.1,
    tackleSuccessPct: 73.5,
    topSpeedKmh: 34.8,
    distanceCoveredKm: 128.2,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'High pressing trigger on opposing left back', notes: 'Forced 3 turnovers in attacking third' }
    ],
    recruitmentNotes: 'Relentless counter-pressing winger with quick change of direction and crossing precision.'
  },
  {
    id: 'p-9',
    number: 9,
    name: 'Dylan Morales',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'ST',
    overallRating: 95,
    height: "6'2\"",
    weight: '182 lbs',
    hometown: 'Monroe, NJ',
    minutesPlayed: 1110,
    matchesPlayed: 13,
    goals: 15,
    assists: 4,
    expectedGoals: 13.8,
    expectedAssists: 3.2,
    passCompletionPct: 81.6,
    tackleSuccessPct: 65.0,
    topSpeedKmh: 34.7,
    distanceCoveredKm: 125.7,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Hold up play against central defenders and finish in the box', notes: 'Scored 82nd minute match-winner, 2 goals on the day' }
    ],
    recruitmentNotes: 'MAPL Golden Boot leader. Complete #9: aerial dominance, hold-up strength, explosive finishing off both feet.'
  },
  // Bench / Key Reserves
  {
    id: 'p-00',
    number: 0,
    name: 'Marcus Chen',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'GK',
    overallRating: 83,
    height: "6'1\"",
    weight: '175 lbs',
    hometown: 'Plainsboro, NJ',
    minutesPlayed: 90,
    matchesPlayed: 2,
    goals: 0,
    assists: 0,
    expectedGoals: 0,
    expectedAssists: 0,
    passCompletionPct: 80.0,
    tackleSuccessPct: 85.0,
    topSpeedKmh: 26.5,
    distanceCoveredKm: 8.5,
    assignmentHistory: [],
    recruitmentNotes: 'Quick reaction shot-stopper with solid distribution.'
  },
  {
    id: 'p-12',
    number: 12,
    name: 'Samira Patel',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'CM',
    overallRating: 84,
    height: "5'8\"",
    weight: '150 lbs',
    hometown: 'Princeton Junction, NJ',
    minutesPlayed: 520,
    matchesPlayed: 10,
    goals: 2,
    assists: 3,
    expectedGoals: 1.8,
    expectedAssists: 2.7,
    passCompletionPct: 89.4,
    tackleSuccessPct: 76.0,
    topSpeedKmh: 31.5,
    distanceCoveredKm: 68.2,
    assignmentHistory: [],
    recruitmentNotes: 'Super sub playmaker who changes tempo immediately off the bench.'
  },
  {
    id: 'p-14',
    number: 14,
    name: 'Noah Kim',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'RB',
    overallRating: 82,
    height: "5'10\"",
    weight: '160 lbs',
    hometown: 'Edison, NJ',
    minutesPlayed: 410,
    matchesPlayed: 9,
    goals: 0,
    assists: 2,
    expectedGoals: 0.3,
    expectedAssists: 1.5,
    passCompletionPct: 83.2,
    tackleSuccessPct: 77.1,
    topSpeedKmh: 33.2,
    distanceCoveredKm: 54.1,
    assignmentHistory: [],
    recruitmentNotes: 'Sturdy 1v1 defensive fullback.'
  },
  {
    id: 'p-15',
    number: 15,
    name: 'Carlos Mendez',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'LW',
    overallRating: 83,
    height: "5'9\"",
    weight: '152 lbs',
    hometown: 'Trenton, NJ',
    minutesPlayed: 480,
    matchesPlayed: 10,
    goals: 3,
    assists: 2,
    expectedGoals: 2.6,
    expectedAssists: 1.9,
    passCompletionPct: 80.5,
    tackleSuccessPct: 67.4,
    topSpeedKmh: 34.2,
    distanceCoveredKm: 61.4,
    assignmentHistory: [],
    recruitmentNotes: 'Tricky dribbler with great burst of speed in transition.'
  },
  {
    id: 'p-16',
    number: 16,
    name: 'Oliver Smith',
    classYear: 'Freshman',
    gradYear: 2030,
    position: 'CB',
    overallRating: 80,
    height: "6'2\"",
    weight: '172 lbs',
    hometown: 'Allentown, NJ',
    minutesPlayed: 320,
    matchesPlayed: 7,
    goals: 0,
    assists: 0,
    expectedGoals: 0.2,
    expectedAssists: 0.1,
    passCompletionPct: 84.0,
    tackleSuccessPct: 80.2,
    topSpeedKmh: 31.8,
    distanceCoveredKm: 39.8,
    assignmentHistory: [],
    recruitmentNotes: 'Tall, disciplined rookie defender with immense physical potential.'
  },
  {
    id: 'p-17',
    number: 17,
    name: 'Jack Turner',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CDM',
    overallRating: 83,
    height: "6'0\"",
    weight: '170 lbs',
    hometown: 'Holmdel, NJ',
    minutesPlayed: 450,
    matchesPlayed: 11,
    goals: 1,
    assists: 1,
    expectedGoals: 0.7,
    expectedAssists: 1.1,
    passCompletionPct: 87.5,
    tackleSuccessPct: 82.0,
    topSpeedKmh: 31.9,
    distanceCoveredKm: 58.7,
    assignmentHistory: [],
    recruitmentNotes: 'Physical ball-winner and destroyer in defensive midfield.'
  },
  {
    id: 'p-18',
    number: 18,
    name: 'Aaron Brooks',
    classYear: 'Freshman',
    gradYear: 2030,
    position: 'ST',
    overallRating: 81,
    height: "6'0\"",
    weight: '168 lbs',
    hometown: 'Pennington, NJ',
    minutesPlayed: 290,
    matchesPlayed: 8,
    goals: 2,
    assists: 1,
    expectedGoals: 2.1,
    expectedAssists: 0.8,
    passCompletionPct: 78.4,
    tackleSuccessPct: 62.0,
    topSpeedKmh: 33.6,
    distanceCoveredKm: 36.2,
    assignmentHistory: [],
    recruitmentNotes: 'Poacher mentality, natural striker instincts in the penalty box.'
  },
  {
    id: 'p-19',
    number: 19,
    name: 'Henry Ward',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CB',
    overallRating: 82,
    height: "6'1\"",
    weight: '176 lbs',
    hometown: 'Lawrenceville, NJ',
    minutesPlayed: 360,
    matchesPlayed: 8,
    goals: 1,
    assists: 0,
    expectedGoals: 0.6,
    expectedAssists: 0.2,
    passCompletionPct: 85.0,
    tackleSuccessPct: 81.3,
    topSpeedKmh: 31.4,
    distanceCoveredKm: 42.1,
    assignmentHistory: [],
    recruitmentNotes: 'Reliable backup center back with aggressive marking.'
  },
  {
    id: 'p-20',
    number: 20,
    name: 'Gabriel Santos',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'CAM',
    overallRating: 83,
    height: "5'8\"",
    weight: '148 lbs',
    hometown: 'Hamilton, NJ',
    minutesPlayed: 380,
    matchesPlayed: 9,
    goals: 2,
    assists: 3,
    expectedGoals: 1.9,
    expectedAssists: 2.5,
    passCompletionPct: 86.2,
    tackleSuccessPct: 68.0,
    topSpeedKmh: 32.7,
    distanceCoveredKm: 48.9,
    assignmentHistory: [],
    recruitmentNotes: 'Brazilian-style footwork, crafty through-ball specialist.'
  },
  {
    id: 'p-21',
    number: 21,
    name: 'Benjamin Cole',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'LB',
    overallRating: 81,
    height: "5'9\"",
    weight: '155 lbs',
    hometown: 'Freehold, NJ',
    minutesPlayed: 310,
    matchesPlayed: 7,
    goals: 0,
    assists: 1,
    expectedGoals: 0.1,
    expectedAssists: 1.2,
    passCompletionPct: 82.0,
    tackleSuccessPct: 75.0,
    topSpeedKmh: 33.0,
    distanceCoveredKm: 39.4,
    assignmentHistory: [],
    recruitmentNotes: 'Tenacious tackler with good recovery pace.'
  },
  {
    id: 'p-22',
    number: 22,
    name: 'Jordan Lee',
    classYear: 'Freshman',
    gradYear: 2030,
    position: 'RW',
    overallRating: 80,
    height: "5'8\"",
    weight: '146 lbs',
    hometown: 'Short Hills, NJ',
    minutesPlayed: 240,
    matchesPlayed: 6,
    goals: 1,
    assists: 2,
    expectedGoals: 1.1,
    expectedAssists: 1.8,
    passCompletionPct: 81.0,
    tackleSuccessPct: 66.0,
    topSpeedKmh: 34.0,
    distanceCoveredKm: 31.5,
    assignmentHistory: [],
    recruitmentNotes: 'Dynamic speedster with sharp cutback ability.'
  },
  {
    id: 'p-23',
    number: 23,
    name: 'Ryan Scott',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CM',
    overallRating: 82,
    height: "5'10\"",
    weight: '162 lbs',
    hometown: 'Skillman, NJ',
    minutesPlayed: 400,
    matchesPlayed: 9,
    goals: 1,
    assists: 2,
    expectedGoals: 1.0,
    expectedAssists: 1.7,
    passCompletionPct: 88.0,
    tackleSuccessPct: 74.0,
    topSpeedKmh: 31.6,
    distanceCoveredKm: 52.0,
    assignmentHistory: [],
    recruitmentNotes: 'Box-to-box worker with high tactical discipline.'
  },
  {
    id: 'p-24',
    number: 24,
    name: 'William Evans',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'ST',
    overallRating: 82,
    height: "6'1\"",
    weight: '175 lbs',
    hometown: 'Robbinsville, NJ',
    minutesPlayed: 350,
    matchesPlayed: 9,
    goals: 3,
    assists: 1,
    expectedGoals: 2.8,
    expectedAssists: 0.9,
    passCompletionPct: 79.5,
    tackleSuccessPct: 64.0,
    topSpeedKmh: 33.4,
    distanceCoveredKm: 44.2,
    assignmentHistory: [],
    recruitmentNotes: 'Direct physical target with great aerial presence.'
  }
];

export const PEDDIE_SCHEDULE_2026_2027: MatchFixture[] = [
  {
    id: 'm-1',
    season: '2026-2027',
    matchDate: 'Sept 16, 2026',
    opponent: 'The Lawrenceville School',
    opponentLogoText: 'LVR',
    isHome: true,
    isConference: true,
    rivalryName: 'Big Red MAPL Opener',
    status: 'Completed',
    peddieScore: 3,
    opponentScore: 1,
    expectedGoalsPeddie: 2.65,
    expectedGoalsOpponent: 1.12,
    possessionPctPeddie: 58.4,
    fieldTiltPctPeddie: 64.2,
    keySummary: 'Dominant second half with goals from Morales, Rossi, and Dupont. Field tilt of 64% suffocated Lawrenceville counter-attacks.'
  },
  {
    id: 'm-2',
    season: '2026-2027',
    matchDate: 'Sept 23, 2026',
    opponent: 'The Hun School of Princeton',
    opponentLogoText: 'HUN',
    isHome: false,
    isConference: true,
    status: 'Completed',
    peddieScore: 2,
    opponentScore: 0,
    expectedGoalsPeddie: 2.10,
    expectedGoalsOpponent: 0.68,
    possessionPctPeddie: 54.2,
    fieldTiltPctPeddie: 59.0,
    keySummary: 'Clean sheet anchored by Julian Vance and Liam O\'Connor. High press trapped Hun inside their own 18-yard box.'
  },
  {
    id: 'm-3',
    season: '2026-2027',
    matchDate: 'Sept 30, 2026',
    opponent: 'The Pennington School',
    opponentLogoText: 'PEN',
    isHome: true,
    isConference: false,
    status: 'Completed',
    peddieScore: 2,
    opponentScore: 2,
    expectedGoalsPeddie: 2.44,
    expectedGoalsOpponent: 1.85,
    possessionPctPeddie: 51.0,
    fieldTiltPctPeddie: 53.5,
    keySummary: 'High-octane non-conference showcase against #2 ranked Prep squad. Late equalizer by Dylan Morales 88th min.'
  },
  {
    id: 'm-4',
    season: '2026-2027',
    matchDate: 'Oct 7, 2026',
    opponent: 'Mercersburg Academy',
    opponentLogoText: 'MER',
    isHome: false,
    isConference: true,
    status: 'Completed',
    peddieScore: 4,
    opponentScore: 1,
    expectedGoalsPeddie: 3.42,
    expectedGoalsOpponent: 0.95,
    possessionPctPeddie: 62.1,
    fieldTiltPctPeddie: 68.4,
    keySummary: 'Total offensive masterclass. Mateo Rossi notched 3 assists via split through-balls.'
  },
  {
    id: 'm-5',
    season: '2026-2027',
    matchDate: 'Oct 14, 2026',
    opponent: 'The Hill School',
    opponentLogoText: 'HIL',
    isHome: true,
    isConference: true,
    status: 'Completed',
    peddieScore: 1,
    opponentScore: 0,
    expectedGoalsPeddie: 1.58,
    expectedGoalsOpponent: 0.74,
    possessionPctPeddie: 56.5,
    fieldTiltPctPeddie: 61.2,
    keySummary: 'Gritty tactical battle. Mateo Rossi scored an audacious 28-yard direct free kick.'
  },
  {
    id: 'm-6',
    season: '2026-2027',
    matchDate: 'Nov 7, 2026',
    opponent: 'Blair Academy',
    opponentLogoText: 'BLR',
    isHome: true,
    isConference: true,
    rivalryName: 'Peddie-Blair Day 2026 (123rd Edition)',
    status: 'Live',
    peddieScore: 2,
    opponentScore: 1,
    expectedGoalsPeddie: 1.84,
    expectedGoalsOpponent: 0.92,
    possessionPctPeddie: 57.8,
    fieldTiltPctPeddie: 65.0,
    keySummary: 'Peddie-Blair Day Championship Match. Minute 74: Peddie leads 2-1 after Dylan Morales clinical half-volley off Alex Rivera delivery!'
  },
  {
    id: 'm-7',
    season: '2026-2027',
    matchDate: 'Nov 14, 2026',
    opponent: 'NJISAA Prep A State Championship',
    opponentLogoText: 'NJ-A',
    isHome: false,
    isConference: false,
    status: 'Upcoming',
    expectedGoalsPeddie: 0,
    expectedGoalsOpponent: 0,
    possessionPctPeddie: 0,
    fieldTiltPctPeddie: 0,
    keySummary: 'State Championship Final scheduled at neutral site.'
  }
];

export const FORMATIONS_CONFIG: Record<string, FormationConfig> = {
  '4-3-3': {
    id: '4-3-3',
    name: '4-3-3 Attacking Possession (Peddie Default)',
    description: 'High wingers, single pivot CDM (#6 Bell) and overlapping fullbacks (#3 Rivera, #2 Zhang). Dominates central progression and half-space penetration.',
    strengths: ['High positional flexibility', 'Overloading opponent fullbacks', 'Fluid half-space triangles'],
    vulnerabilities: ['Wide spaces behind attacking fullbacks', 'Requires high aerobic recovery sprint load'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: "O'Connor", xPct: 50, yPct: 92, role: 'Sweeper Keeper' },
      { position: 'LB', playerNumber: 3, playerName: 'Rivera', xPct: 15, yPct: 74, role: 'Inverted Wingback' },
      { position: 'CB', playerNumber: 5, playerName: 'Davies', xPct: 38, yPct: 78, role: 'Covering Defender' },
      { position: 'CB', playerNumber: 4, playerName: 'Vance', xPct: 62, yPct: 78, role: 'Ball-Playing Stopper' },
      { position: 'RB', playerNumber: 2, playerName: 'Zhang', xPct: 85, yPct: 74, role: 'Overlapping Fullback' },
      { position: 'CDM', playerNumber: 6, playerName: 'Bell', xPct: 50, yPct: 58, role: 'Deep-Lying Anchor' },
      { position: 'CM', playerNumber: 8, playerName: 'Rossi', xPct: 34, yPct: 44, role: 'Mezzala Playmaker' },
      { position: 'CAM', playerNumber: 10, playerName: 'Sterling', xPct: 66, yPct: 42, role: 'Advanced Free 10' },
      { position: 'LW', playerNumber: 11, playerName: 'Dupont', xPct: 18, yPct: 24, role: 'Inside Forward' },
      { position: 'ST', playerNumber: 9, playerName: 'Morales', xPct: 50, yPct: 16, role: 'Complete Forward' },
      { position: 'RW', playerNumber: 7, playerName: 'Brooks', xPct: 82, yPct: 24, role: 'Touchline Winger' }
    ]
  },
  '4-2-3-1': {
    id: '4-2-3-1',
    name: '4-2-3-1 Gegenpressing Double Pivot',
    description: 'Double pivot with #6 Bell and #17 Turner shielding backline, liberating #10 Sterling to conduct rapid counter-attacks.',
    strengths: ['Unbreakable central transition defense', 'Explosive 4-man counter-attack waves'],
    vulnerabilities: ['Can leave striker isolated against 3-man backline'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: "O'Connor", xPct: 50, yPct: 92, role: 'Sweeper Keeper' },
      { position: 'LB', playerNumber: 3, playerName: 'Rivera', xPct: 16, yPct: 75, role: 'Fullback' },
      { position: 'CB', playerNumber: 5, playerName: 'Davies', xPct: 38, yPct: 80, role: 'Center Back' },
      { position: 'CB', playerNumber: 4, playerName: 'Vance', xPct: 62, yPct: 80, role: 'Center Back' },
      { position: 'RB', playerNumber: 2, playerName: 'Zhang', xPct: 84, yPct: 75, role: 'Fullback' },
      { position: 'CDM', playerNumber: 6, playerName: 'Bell', xPct: 38, yPct: 60, role: 'Double Pivot Left' },
      { position: 'CDM', playerNumber: 17, playerName: 'Turner', xPct: 62, yPct: 60, role: 'Double Pivot Right' },
      { position: 'CAM', playerNumber: 10, playerName: 'Sterling', xPct: 50, yPct: 38, role: 'Central Playmaker' },
      { position: 'LW', playerNumber: 11, playerName: 'Dupont', xPct: 18, yPct: 26, role: 'Left Winger' },
      { position: 'ST', playerNumber: 9, playerName: 'Morales', xPct: 50, yPct: 15, role: 'Striker' },
      { position: 'RW', playerNumber: 7, playerName: 'Brooks', xPct: 82, yPct: 26, role: 'Right Winger' }
    ]
  },
  '3-5-2': {
    id: '3-5-2',
    name: '3-5-2 Wing-Back Overload & Twin Strikers',
    description: 'Triple central defense with wingbacks providing width; twin strikers (#9 Morales and #18 Brooks) pin opposing center backs.',
    strengths: ['Complete midfield superiority (5v3)', 'Twin striker box presence'],
    vulnerabilities: ['Flanks exposed if wingbacks are caught high up'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: "O'Connor", xPct: 50, yPct: 92, role: 'Goalkeeper' },
      { position: 'CB', playerNumber: 16, playerName: 'Smith', xPct: 28, yPct: 78, role: 'Left Center Back' },
      { position: 'CB', playerNumber: 4, playerName: 'Vance', xPct: 50, yPct: 80, role: 'Sweeper / Libero' },
      { position: 'CB', playerNumber: 5, playerName: 'Davies', xPct: 72, yPct: 78, role: 'Right Center Back' },
      { position: 'LB', playerNumber: 3, playerName: 'Rivera', xPct: 12, yPct: 52, role: 'Left Wing-Back' },
      { position: 'CDM', playerNumber: 6, playerName: 'Bell', xPct: 50, yPct: 56, role: 'Central Midfielder' },
      { position: 'CM', playerNumber: 8, playerName: 'Rossi', xPct: 34, yPct: 44, role: 'Central Midfielder' },
      { position: 'CAM', playerNumber: 10, playerName: 'Sterling', xPct: 66, yPct: 44, role: 'Attacking Midfielder' },
      { position: 'RB', playerNumber: 2, playerName: 'Zhang', xPct: 88, yPct: 52, role: 'Right Wing-Back' },
      { position: 'ST', playerNumber: 9, playerName: 'Morales', xPct: 38, yPct: 18, role: 'Target Striker' },
      { position: 'ST', playerNumber: 18, playerName: 'Brooks A', xPct: 62, yPct: 18, role: 'Second Striker' }
    ]
  },
  '4-4-2': {
    id: '4-4-2',
    name: '4-4-2 Compact Low Block (Late Game Lockout)',
    description: 'Rigid two-bank defensive block of 4 with tight 12-meter line spacing to deny central passing channels when protecting 1-goal lead.',
    strengths: ['Maximum compactness', 'Zero central half-space gaps', 'Easy transition to clearance'],
    vulnerabilities: ['Cedes possession in opposing half', 'Heavy physical work on twin forwards'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: "O'Connor", xPct: 50, yPct: 92, role: 'Goalkeeper' },
      { position: 'LB', playerNumber: 3, playerName: 'Rivera', xPct: 16, yPct: 76, role: 'Left Back' },
      { position: 'CB', playerNumber: 5, playerName: 'Davies', xPct: 38, yPct: 78, role: 'Center Back' },
      { position: 'CB', playerNumber: 4, playerName: 'Vance', xPct: 62, yPct: 78, role: 'Center Back' },
      { position: 'RB', playerNumber: 2, playerName: 'Zhang', xPct: 84, yPct: 76, role: 'Right Back' },
      { position: 'LW', playerNumber: 11, playerName: 'Dupont', xPct: 16, yPct: 50, role: 'Left Midfielder' },
      { position: 'CDM', playerNumber: 6, playerName: 'Bell', xPct: 38, yPct: 52, role: 'Central Midfielder' },
      { position: 'CM', playerNumber: 8, playerName: 'Rossi', xPct: 62, yPct: 52, role: 'Central Midfielder' },
      { position: 'RW', playerNumber: 7, playerName: 'Brooks T', xPct: 84, yPct: 50, role: 'Right Midfielder' },
      { position: 'ST', playerNumber: 9, playerName: 'Morales', xPct: 38, yPct: 24, role: 'Pressing Forward' },
      { position: 'ST', playerNumber: 10, playerName: 'Sterling', xPct: 62, yPct: 24, role: 'Second Striker' }
    ]
  }
};

export const MATCH_EVENTS_LIVE_BLAIR: MatchEvent[] = [
  { id: 'ev-1', minute: 4, second: 12, team: 'Peddie', playerNumber: 8, playerName: 'Mateo Rossi', type: 'Pass', startX: 42, startY: 34, endX: 68, endY: 14, success: true, description: 'Diagonal 35m switch to Xavier Dupont on left wing', phase: 'Open Play' },
  { id: 'ev-2', minute: 7, second: 45, team: 'Peddie', playerNumber: 11, playerName: 'Xavier Dupont', type: 'Cross', startX: 88, startY: 12, endX: 98, endY: 32, success: false, description: 'Whip cross cleared by Blair CB #5', phase: 'Open Play' },
  { id: 'ev-3', minute: 12, second: 18, team: 'Opponent', playerNumber: 9, playerName: 'Blair Striker #9', type: 'Shot', startX: 84, startY: 28, expectedGoals: 0.08, success: false, description: 'Long distance shot deflected over bar', phase: 'Counter Attack' },
  { id: 'ev-4', minute: 18, second: 30, team: 'Peddie', playerNumber: 11, playerName: 'Xavier Dupont', type: 'Goal', startX: 92, startY: 22, expectedGoals: 0.42, success: true, description: 'GOAL! Dupont cuts inside on right foot and bends into top corner (1-0 Peddie)', phase: 'Open Play' },
  { id: 'ev-5', minute: 28, second: 10, team: 'Peddie', playerNumber: 4, playerName: 'Julian Vance', type: 'Tackle', startX: 35, startY: 42, success: true, description: 'Crunching standing tackle on Blair #10 to halt counter', phase: 'High Press' },
  { id: 'ev-6', minute: 34, second: 45, team: 'Peddie', playerNumber: 8, playerName: 'Mateo Rossi', type: 'Corner', startX: 105, startY: 0, endX: 96, endY: 32, success: true, description: 'Inswinging corner to near post', phase: 'Set Piece' },
  { id: 'ev-7', minute: 35, second: 0, team: 'Peddie', playerNumber: 4, playerName: 'Julian Vance', type: 'Shot', startX: 96, startY: 32, expectedGoals: 0.38, success: false, description: 'Header glanced off crossbar', phase: 'Set Piece' },
  { id: 'ev-8', minute: 49, second: 22, team: 'Opponent', playerNumber: 11, playerName: 'Blair Winger #11', type: 'Goal', startX: 88, startY: 42, expectedGoals: 0.34, success: true, description: 'Goal for Blair on rebound scramble inside 6-yard box (1-1)', phase: 'Set Piece' },
  { id: 'ev-9', minute: 62, second: 15, team: 'Peddie', playerNumber: 6, playerName: 'Christian Bell', type: 'Interception', startX: 52, startY: 30, success: true, description: 'Stepped into passing lane to intercept clearance', phase: 'High Press' },
  { id: 'ev-10', minute: 73, second: 40, team: 'Peddie', playerNumber: 3, playerName: 'Alex Rivera', type: 'Key Pass', startX: 86, startY: 8, endX: 98, endY: 30, success: true, description: 'Low drilled cross across face of goal', phase: 'Open Play' },
  { id: 'ev-11', minute: 74, second: 0, team: 'Peddie', playerNumber: 9, playerName: 'Dylan Morales', type: 'Goal', startX: 98, startY: 30, expectedGoals: 0.65, success: true, description: 'GOAL! Clinical half-volley into side netting (2-1 Peddie!)', phase: 'Open Play' }
];

export const MAPL_SCOUTING_REPORTS: Record<string, ScoutingReport> = {
  'Blair Academy': {
    opponent: 'Blair Academy Buccaneers',
    conference: 'MAPL',
    headCoach: 'Blair Coaching Staff',
    formation: '4-4-2',
    keyPlaymakers: ['#9 Target Striker (6\'3", aerial target)', '#10 Central Mid (primary set-piece taker)', '#11 Left Winger (speed in transition)'],
    tendencies: {
      buildup: 'Direct long balls from GK into striker chest; bypasses midfield play.',
      defensiveBlock: 'Low compact 4-4-2 block; rarely press above half field.',
      vulnerabilityZone: 'Half-spaces behind their wide midfielders when they push up on counter.',
      setPieceThreat: 'Long throw-ins directly into penalty area; near-post flicks.'
    },
    recommendedTactics: [
      'Overload their right flank with Rivera and Dupont to draw central defenders out.',
      'Deploy Christian Bell (#6) as second-ball sweeper against long goal kicks.',
      'Transition into compact 4-4-2 after 80th minute to protect lead.'
    ],
    winProbabilityPct: 78.5
  },
  'The Lawrenceville School': {
    opponent: 'The Lawrenceville School Big Red',
    conference: 'MAPL',
    headCoach: 'Lawrenceville Staff',
    formation: '4-3-3',
    keyPlaymakers: ['#8 Creative Pivot', '#7 Inverted Right Winger'],
    tendencies: {
      buildup: 'Short passing from back, high reliance on central midfielders turning under pressure.',
      defensiveBlock: 'Mid-block with aggressive fullback overlaps.',
      vulnerabilityZone: 'Spirited high line vulnerable to Morales runs behind.',
      setPieceThreat: 'Short corner routines to create 2v1 on edge of box.'
    },
    recommendedTactics: [
      'Trigger high press whenever backpass is made to their GK or right CB.',
      'Quick direct balls from Vance into Morales channel runs.'
    ],
    winProbabilityPct: 82.0
  },
  'The Hun School': {
    opponent: 'The Hun School Raiders',
    conference: 'MAPL',
    headCoach: 'Hun Staff',
    formation: '3-5-2',
    keyPlaymakers: ['#10 Striker (explosive acceleration)', '#5 Center Back'],
    tendencies: {
      buildup: 'Wingbacks stay very high; 3 center backs play wide.',
      defensiveBlock: 'Back 5 when defending deep.',
      vulnerabilityZone: 'Enormous space behind wingbacks on quick turnovers.',
      setPieceThreat: 'Tall center backs attacking far post.'
    },
    recommendedTactics: [
      'Isolate their outer center backs 1v1 with our wingers Brooks and Dupont.',
      'Avoid crossing into crowded box of 3 tall CBs; utilize cutbacks to Rossi at 18-yard arc.'
    ],
    winProbabilityPct: 74.0
  }
};

export const SIDELINE_SET_PIECE_PLAYBOOK = {
  attackingCorners: [
    {
      name: 'Falcon Claw (Near Post Overload)',
      triggerSignal: 'Left Hand Raised',
      taker: '#8 Mateo Rossi',
      description: 'Julian Vance (#4) fakes far post then dashes across near post to flick on or head directly into near corner. Morales (#9) crashes 6-yard box for rebounds.',
      probabilityGoalPct: 28.5
    },
    {
      name: 'Gold Horizon (Far Post Deep Curl)',
      triggerSignal: 'Both Hands On Hips',
      taker: '#10 Leo Sterling',
      description: 'Outswinging curler to far post. Davies (#5) blocks goalkeeper sight line while Vance (#4) rises over fullback at back post.',
      probabilityGoalPct: 24.0
    },
    {
      name: 'Highstown Switch (Short Corner Triad)',
      triggerSignal: 'Taps Shinguard',
      taker: '#8 Mateo Rossi & #11 Xavier Dupont',
      description: 'Short pass to Dupont, who lays back to Rivera (#3) arriving at top of box for first-time curling effort.',
      probabilityGoalPct: 21.0
    }
  ],
  defensiveCorners: [
    {
      name: 'Hybrid Zonal Anchor',
      organization: '5 Zonal Protectors + 3 Man-Markers + 1 Short Corner Disruptor + 1 Outlet Sprinter',
      anchor: '#4 Julian Vance on 6-yard central zone',
      outlet: '#11 Xavier Dupont stationed at midfield stripe ready for counter sprint'
    }
  ],
  pressingTriggers: [
    {
      cue: 'Back-pass to Opponent Goalkeeper',
      action: 'Striker Morales sprints at GK kicking foot; Wingers tuck inside to eliminate lateral fullback passes.'
    },
    {
      cue: 'Opponent Facing Own Goal under Pressure',
      action: 'All midfielders step up 10 yards to intercept panic clearance.'
    },
    {
      cue: 'Bouncing Ball or Heavy Touch on Sideline',
      action: 'Nearest fullback and winger double-team; trap ball against touchline.'
    }
  ],
  lateGameLockout: [
    {
      timeWindow: "80' - 90'+",
      formationShift: 'Shift from 4-3-3 to 4-4-2 Compact Low Block',
      rules: [
        'Zero risky passes through central midfield; play into corner flags.',
        'Keep 6 players strictly behind the ball at all times.',
        'All free kicks and throw-ins taken with maximum legal delay.',
        'Goalkeeper Liam O\'Connor holds ball for full allowed count before drop kick.'
      ]
    }
  ]
};
