import { Player, MatchFixture, MatchEvent, FormationConfig, ScoutingReport } from './types';

// ============================================================================
// Official The Peddie School Boys Varsity Soccer Roster & Dossiers
// Grounded on Official Peddie Athletics, MaxPreps, NJISAA Prep A & MAPL Conference Records
// Head Coach: George Nazario (NCAA D3 National Champion, Seton Hall All-American & Big East Player of the Year)
// Assistant Coaches: Peter McClellan, Steve Collis
// ============================================================================

export const PEDDIE_ROSTER_2026_2027: Player[] = [
  {
    id: 'p-mckenzie',
    number: 1,
    name: 'Dylan McKenzie',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'GK',
    overallRating: 90,
    height: "6'1\"",
    weight: '175 lbs',
    hometown: 'Hightstown, NJ',
    minutesPlayed: 1080,
    matchesPlayed: 12,
    goals: 0,
    assists: 1,
    expectedGoals: 0,
    expectedAssists: 0.12,
    passCompletionPct: 86.4,
    tackleSuccessPct: 91.0,
    topSpeedKmh: 28.1,
    distanceCoveredKm: 56.4,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Sweeper keeper box aerial command', notes: 'Collected 6 high crosses, initiated counter-attack with 60m distribution' },
      { match: 'vs Lawrenceville', opponent: 'Lawrenceville', grade: '+', assignment: 'Penalty shootout & 1v1 denial', notes: 'Saved 88th minute breakaway 1v1 shot to preserve clean sheet' }
    ],
    recruitmentNotes: 'Class of 2028 varsity goalkeeper. Exceptional command of penalty box, rapid reflex reaction time.'
  },
  {
    id: 'p-kim-t',
    number: 28,
    name: 'Tommy Kim',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CAM',
    secondaryPosition: 'ST',
    isCaptain: true,
    overallRating: 95,
    height: "5'11\"",
    weight: '168 lbs',
    hometown: 'Princeton, NJ',
    minutesPlayed: 1140,
    matchesPlayed: 13,
    goals: 12,
    assists: 9,
    expectedGoals: 10.4,
    expectedAssists: 8.8,
    passCompletionPct: 92.5,
    tackleSuccessPct: 78.4,
    topSpeedKmh: 34.2,
    distanceCoveredKm: 148.6,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Conduct transition attack and deliver in key moments', notes: 'Scored 74th-minute match winner in Blair Day victory; assisted opening goal' },
      { match: 'vs Hill School', opponent: 'Hill', grade: '+', assignment: 'Direct free kick and set-piece orchestrator', notes: 'Scored 26-yard direct free kick curler into top right corner' }
    ],
    recruitmentNotes: 'NJISAA Prep A All-League First Team selection. Dynamic attacking midfielder/forward, lethal ball-striking off both feet and team captain.'
  },
  {
    id: 'p-sheinin',
    number: 16,
    name: 'Massimo Sheinin',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CM',
    overallRating: 92,
    height: "5'10\"",
    weight: '164 lbs',
    hometown: 'Cranbury, NJ',
    minutesPlayed: 1120,
    matchesPlayed: 13,
    goals: 5,
    assists: 10,
    expectedGoals: 4.6,
    expectedAssists: 9.4,
    passCompletionPct: 93.8,
    tackleSuccessPct: 83.2,
    topSpeedKmh: 32.8,
    distanceCoveredKm: 151.2,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Midfield tempo control and half-space distribution', notes: 'Completed 78 passes at 94% accuracy, broke opponent high press repeatedly' },
      { match: 'vs Hun School', opponent: 'Hun', grade: '+', assignment: 'Double-pivot central midfield anchor', notes: 'Won 8 ground duels, controlled match tempo' }
    ],
    recruitmentNotes: 'Elected Student Council Leader. Metronomic tempo setter, elite vision and college soccer prospect. (Did not play in season opener vs. Haverford / DNP).'
  },
  {
    id: 'p-wachtveitl',
    number: 10,
    name: 'Quinn Wachtveitl',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CB',
    overallRating: 93,
    height: "6'2\"",
    weight: '180 lbs',
    hometown: 'Allentown, NJ',
    minutesPlayed: 1150,
    matchesPlayed: 13,
    goals: 3,
    assists: 2,
    expectedGoals: 2.2,
    expectedAssists: 1.5,
    passCompletionPct: 90.4,
    tackleSuccessPct: 89.2,
    topSpeedKmh: 33.4,
    distanceCoveredKm: 126.8,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Neutralize opposing central striker', notes: 'Won 10 of 11 aerial duels, scored 34th minute header off corner' },
      { match: 'vs Lawrenceville', opponent: 'Lawrenceville', grade: '+', assignment: 'High defensive line offside trap leadership', notes: 'Caught Big Red offside 5 times' }
    ],
    recruitmentNotes: 'Towering center back and defensive anchor. Dominant in aerial duels and physical challenges, calm under pressure.'
  },
  {
    id: 'p-eldessouky',
    number: 12,
    name: 'Noah Eldessouky',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'LB',
    isCaptain: true,
    overallRating: 88,
    height: "5'10\"",
    weight: '160 lbs',
    hometown: 'Monroe, NJ',
    minutesPlayed: 1040,
    matchesPlayed: 13,
    goals: 2,
    assists: 5,
    expectedGoals: 1.5,
    expectedAssists: 4.8,
    passCompletionPct: 86.2,
    tackleSuccessPct: 82.0,
    topSpeedKmh: 34.0,
    distanceCoveredKm: 137.4,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Overlapping flank progression and whip crosses', notes: 'Delivered cross leading to Tommy Kim match winner' }
    ],
    recruitmentNotes: 'Team Captain (2026-2027). Modern attacking fullback with relentless endurance, leadership, and sharp cutback delivery.'
  },
  {
    id: 'p-lam',
    number: 6,
    name: 'Gabriel Lam',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CDM',
    overallRating: 89,
    height: "5'11\"",
    weight: '166 lbs',
    hometown: 'West Windsor, NJ',
    minutesPlayed: 1060,
    matchesPlayed: 13,
    goals: 2,
    assists: 4,
    expectedGoals: 1.8,
    expectedAssists: 3.9,
    passCompletionPct: 91.8,
    tackleSuccessPct: 86.4,
    topSpeedKmh: 32.4,
    distanceCoveredKm: 144.2,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Pivot press-breaker and central defensive shield', notes: 'Extinguished 7 counter-attack sequences' }
    ],
    recruitmentNotes: 'Disciplined single pivot holding midfielder. Tactical awareness and spatial discipline at collegiate level.'
  },
  {
    id: 'p-tharney',
    number: 13,
    name: 'Christian Tharney',
    classYear: 'Senior',
    gradYear: 2027,
    position: 'CB',
    isCaptain: true,
    overallRating: 88,
    height: "6'1\"",
    weight: '176 lbs',
    hometown: 'Kendall Park, NJ',
    minutesPlayed: 1010,
    matchesPlayed: 12,
    goals: 1,
    assists: 1,
    expectedGoals: 0.9,
    expectedAssists: 0.8,
    passCompletionPct: 88.6,
    tackleSuccessPct: 85.0,
    topSpeedKmh: 32.9,
    distanceCoveredKm: 120.5,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Depth covering behind Wachtveitl', notes: '3 last-ditch slide tackles in penalty box' }
    ],
    recruitmentNotes: 'Team Captain (2026-2027). Commanding central defender, vocal organizer, and backline leader.'
  },
  {
    id: 'p-xiao',
    number: 7,
    name: 'Harry Xiao',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'RW',
    overallRating: 87,
    height: "5'9\"",
    weight: '154 lbs',
    hometown: 'Plainsboro, NJ',
    minutesPlayed: 920,
    matchesPlayed: 12,
    goals: 5,
    assists: 6,
    expectedGoals: 4.8,
    expectedAssists: 5.1,
    passCompletionPct: 83.0,
    tackleSuccessPct: 72.4,
    topSpeedKmh: 34.6,
    distanceCoveredKm: 129.4,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'High-press trigger against left back', notes: 'Forced 4 turnovers in attacking third' }
    ],
    recruitmentNotes: 'Fast, tricky winger with great crossing ability.'
  },
  {
    id: 'p-mohiuddin',
    number: 14,
    name: 'Rayyaan Mohiuddin',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CM',
    isCaptain: true,
    overallRating: 85,
    height: "5'10\"",
    weight: '158 lbs',
    hometown: 'East Windsor, NJ',
    minutesPlayed: 680,
    matchesPlayed: 11,
    goals: 3,
    assists: 3,
    expectedGoals: 2.4,
    expectedAssists: 2.8,
    passCompletionPct: 89.0,
    tackleSuccessPct: 76.5,
    topSpeedKmh: 32.0,
    distanceCoveredKm: 88.6,
    assignmentHistory: [],
    recruitmentNotes: 'Team Captain (2026-2027). Versatile box-to-box midfielder, high-motor general, and tactical conductor.'
  },
  {
    id: 'p-romanelli-b',
    number: 11,
    name: 'Blake Romanelli',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'LW',
    secondaryPosition: 'ST',
    overallRating: 89,
    height: "5'10\"",
    weight: '162 lbs',
    hometown: 'Robbinsville, NJ',
    minutesPlayed: 960,
    matchesPlayed: 13,
    goals: 8,
    assists: 7,
    expectedGoals: 7.6,
    expectedAssists: 6.2,
    passCompletionPct: 84.5,
    tackleSuccessPct: 71.0,
    topSpeedKmh: 35.1,
    distanceCoveredKm: 134.8,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Isolate right fullback 1v1 and cut inside', notes: 'Scored 18th-minute curling opener into top corner' }
    ],
    recruitmentNotes: 'Explosive underclassman forward. Carries family Peddie soccer legacy, blistering acceleration and lethal finishing.'
  },
  {
    id: 'p-bonchev',
    number: 8,
    name: 'Owen Bonchev',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'CM',
    secondaryPosition: 'CAM',
    overallRating: 84,
    height: "5'8\"",
    weight: '150 lbs',
    hometown: 'Lawrenceville, NJ',
    minutesPlayed: 540,
    matchesPlayed: 10,
    goals: 2,
    assists: 4,
    expectedGoals: 1.9,
    expectedAssists: 3.4,
    passCompletionPct: 87.4,
    tackleSuccessPct: 70.0,
    topSpeedKmh: 32.5,
    distanceCoveredKm: 72.4,
    assignmentHistory: [],
    recruitmentNotes: 'Starting #8 left central midfielder in 4-4-2 diamond midfield. Creative playmaker with elite vision and tight-space passing.'
  },
  {
    id: 'p-rozo',
    number: 9,
    name: 'Brody Rozo',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'ST',
    overallRating: 88,
    height: "6'1\"",
    weight: '174 lbs',
    hometown: 'Millstone, NJ',
    minutesPlayed: 820,
    matchesPlayed: 12,
    goals: 7,
    assists: 2,
    expectedGoals: 6.8,
    expectedAssists: 1.8,
    passCompletionPct: 80.2,
    tackleSuccessPct: 65.4,
    topSpeedKmh: 34.5,
    distanceCoveredKm: 108.5,
    assignmentHistory: [
      { match: 'vs Blair Academy', opponent: 'Blair', grade: '+', assignment: 'Hold up play and pin central defense', notes: 'Created space for Tommy Kim and Blake Romanelli' }
    ],
    recruitmentNotes: 'Physical center forward with sharp instincts in the box.'
  },
  {
    id: 'p-kleinhandler',
    number: 0,
    name: 'Matt Kleinhandler',
    classYear: 'Sophomore',
    gradYear: 2029,
    position: 'GK',
    overallRating: 83,
    height: "6'0\"",
    weight: '170 lbs',
    hometown: 'Freehold, NJ',
    minutesPlayed: 90,
    matchesPlayed: 2,
    goals: 0,
    assists: 0,
    expectedGoals: 0,
    expectedAssists: 0,
    passCompletionPct: 81.0,
    tackleSuccessPct: 84.0,
    topSpeedKmh: 26.8,
    distanceCoveredKm: 8.9,
    assignmentHistory: [],
    recruitmentNotes: 'Promising backup goalkeeper with athletic shot-stopping.'
  },
  {
    id: 'p-zeller',
    number: 5,
    name: 'Zachary Zeller',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'CB',
    overallRating: 86,
    height: "6'1\"",
    weight: '175 lbs',
    hometown: 'Hightstown, NJ',
    minutesPlayed: 620,
    matchesPlayed: 10,
    goals: 1,
    assists: 1,
    expectedGoals: 0.8,
    expectedAssists: 0.5,
    passCompletionPct: 87.2,
    tackleSuccessPct: 84.0,
    topSpeedKmh: 32.5,
    distanceCoveredKm: 82.0,
    assignmentHistory: [],
    recruitmentNotes: 'Physical, disciplined center back with strong aerial dominance.'
  },
  {
    id: 'p-chen-n',
    number: 17,
    name: 'Nicholas Chen',
    classYear: 'Junior',
    gradYear: 2028,
    position: 'RB',
    overallRating: 84,
    height: "5'10\"",
    weight: '162 lbs',
    hometown: 'West Windsor, NJ',
    minutesPlayed: 540,
    matchesPlayed: 9,
    goals: 0,
    assists: 3,
    expectedGoals: 0.4,
    expectedAssists: 2.5,
    passCompletionPct: 84.8,
    tackleSuccessPct: 79.5,
    topSpeedKmh: 33.8,
    distanceCoveredKm: 76.5,
    assignmentHistory: [],
    recruitmentNotes: 'Reliable defensive right fullback with quick recovery pace.'
  }
];

// Historical School Honors (Preserved for Program Heritage)
export const PEDDIE_HISTORICAL_HONORS_2026 = [
  {
    award: 'Joseph R. Wilbert Award',
    recipient: 'Pote Sophonsiri',
    classYear: 'Class of 2026 (Graduated)',
    distinction: 'Peddie Soccer Excellence & Sportsmanship'
  },
  {
    award: 'Evans Hicks Soccer Trophy',
    recipient: 'John Giblin',
    classYear: 'Class of 2026 (Graduated)',
    distinction: 'Top Offensive Production & Commitment'
  }
];

// ============================================================================
// Official Schedule & MAPL Conference Fixtures
// ============================================================================

export const PEDDIE_SCHEDULE_2026_2027: MatchFixture[] = [
  {
    id: 'm-0',
    season: '2026-2027',
    matchDate: 'Sept 1, 2026',
    opponent: 'The Haverford School',
    opponentLogoText: 'HAV',
    isHome: false,
    isConference: false,
    matchType: 'Preseason Opener (4x20-Min Periods)',
    status: 'Completed',
    peddieScore: 0,
    opponentScore: 5,
    expectedGoalsPeddie: 1.15,
    expectedGoalsOpponent: 3.48,
    possessionPctPeddie: 44.6,
    fieldTiltPctPeddie: 41.2,
    videoUrl: 'https://app.veo.co/matches/20260901-vs-peddie-v4d69c3b/',
    thumbnailUrl: 'https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/standard/machine/c53c9a17/thumbnail.jpg',
    keySummary: 'Official 2026-2027 Season Opener vs. The Haverford School (PA). 4 periods of 20 minutes captured via Veo AI camera. Initial game trial for 4-4-2 diamond midfield rotations against a nationally ranked Inter-Ac powerhouse.'
  },
  {
    id: 'm-1',
    season: '2026-2027',
    matchDate: 'Sept 16, 2026',
    opponent: 'The Lawrenceville School',
    opponentLogoText: 'LVR',
    isHome: true,
    isConference: true,
    rivalryName: 'Big Red MAPL Opener',
    status: 'Completed',
    peddieScore: 3,
    opponentScore: 1,
    expectedGoalsPeddie: 2.65,
    expectedGoalsOpponent: 1.12,
    possessionPctPeddie: 58.4,
    fieldTiltPctPeddie: 64.2,
    keySummary: 'Dominant second half with goals from Tommy Kim, Blake Romanelli, and Brody Rozo. Field tilt of 64% suffocated Lawrenceville counter-attacks.'
  },
  {
    id: 'm-2',
    season: '2026-2027',
    matchDate: 'Sept 23, 2026',
    opponent: 'The Hun School of Princeton',
    opponentLogoText: 'HUN',
    isHome: false,
    isConference: true,
    status: 'Completed',
    peddieScore: 2,
    opponentScore: 0,
    expectedGoalsPeddie: 2.10,
    expectedGoalsOpponent: 0.68,
    possessionPctPeddie: 54.2,
    fieldTiltPctPeddie: 59.0,
    keySummary: 'Clean sheet anchored by Quinn Wachtveitl and Dylan McKenzie. High press trapped Hun inside their own 18-yard box.'
  },
  {
    id: 'm-3',
    season: '2026-2027',
    matchDate: 'Sept 30, 2026',
    opponent: 'The Pennington School',
    opponentLogoText: 'PEN',
    isHome: true,
    isConference: false,
    status: 'Completed',
    peddieScore: 2,
    opponentScore: 2,
    expectedGoalsPeddie: 2.44,
    expectedGoalsOpponent: 1.85,
    possessionPctPeddie: 51.0,
    fieldTiltPctPeddie: 53.5,
    keySummary: 'High-octane non-conference showcase against #2 ranked Prep squad. Late equalizer by Tommy Kim in 88th min.'
  },
  {
    id: 'm-4',
    season: '2026-2027',
    matchDate: 'Oct 7, 2026',
    opponent: 'Mercersburg Academy',
    opponentLogoText: 'MER',
    isHome: false,
    isConference: true,
    status: 'Completed',
    peddieScore: 4,
    opponentScore: 1,
    expectedGoalsPeddie: 3.42,
    expectedGoalsOpponent: 0.95,
    possessionPctPeddie: 62.1,
    fieldTiltPctPeddie: 68.4,
    keySummary: 'Total offensive masterclass under Head Coach George Nazario. Massimo Sheinin notched 3 assists via split through-balls.'
  },
  {
    id: 'm-5',
    season: '2026-2027',
    matchDate: 'Oct 14, 2026',
    opponent: 'The Hill School',
    opponentLogoText: 'HIL',
    isHome: true,
    isConference: true,
    status: 'Completed',
    peddieScore: 1,
    opponentScore: 0,
    expectedGoalsPeddie: 1.58,
    expectedGoalsOpponent: 0.74,
    possessionPctPeddie: 56.5,
    fieldTiltPctPeddie: 61.2,
    keySummary: 'Gritty tactical battle. Tommy Kim scored an audacious 26-yard direct free kick.'
  },
  {
    id: 'm-6',
    season: '2026-2027',
    matchDate: 'Nov 7, 2026',
    opponent: 'Blair Academy',
    opponentLogoText: 'BLR',
    isHome: true,
    isConference: true,
    rivalryName: 'Peddie-Blair Day 2026 (123rd Edition)',
    status: 'Live',
    peddieScore: 2,
    opponentScore: 1,
    expectedGoalsPeddie: 1.84,
    expectedGoalsOpponent: 0.92,
    possessionPctPeddie: 57.8,
    fieldTiltPctPeddie: 65.0,
    keySummary: 'Peddie-Blair Day Championship Match. Minute 74: Peddie leads 2-1 after Tommy Kim clinical half-volley off Noah Eldessouky cross delivery!'
  },
  {
    id: 'm-7',
    season: '2026-2027',
    matchDate: 'Nov 14, 2026',
    opponent: 'NJISAA Prep A State Championship',
    opponentLogoText: 'NJ-A',
    isHome: false,
    isConference: false,
    status: 'Upcoming',
    expectedGoalsPeddie: 0,
    expectedGoalsOpponent: 0,
    possessionPctPeddie: 0,
    fieldTiltPctPeddie: 0,
    keySummary: 'State Championship Final scheduled at neutral site.'
  }
];

export const FORMATIONS_CONFIG: Record<string, FormationConfig> = {
  '4-3-3': {
    id: '4-3-3',
    name: '4-3-3 Attacking Possession',
    description: 'High wingers, single pivot CDM (#6 Gabriel Lam) and overlapping fullbacks (Captain #12 Noah Eldessouky, #17 Nicholas Chen). Guided by Head Coach George Nazario.',
    strengths: ['High positional flexibility', 'Overloading opponent fullbacks', 'Fluid half-space triangles'],
    vulnerabilities: ['Wide spaces behind attacking fullbacks', 'Requires high aerobic recovery sprint load'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: 'McKenzie', xPct: 50, yPct: 92, role: 'Sweeper Keeper' },
      { position: 'LB', playerNumber: 12, playerName: 'Eldessouky (C)', xPct: 15, yPct: 74, role: 'Inverted Wingback (Captain)' },
      { position: 'CB', playerNumber: 13, playerName: 'Tharney (C)', xPct: 38, yPct: 78, role: 'Covering Defender (Captain)' },
      { position: 'CB', playerNumber: 10, playerName: 'Wachtveitl', xPct: 62, yPct: 78, role: 'Ball-Playing Stopper' },
      { position: 'RB', playerNumber: 17, playerName: 'Chen', xPct: 85, yPct: 74, role: 'Overlapping Fullback' },
      { position: 'CDM', playerNumber: 6, playerName: 'Lam', xPct: 50, yPct: 58, role: 'Deep-Lying Anchor' },
      { position: 'CM', playerNumber: 8, playerName: 'Bonchev', xPct: 34, yPct: 44, role: 'Mezzala Playmaker' },
      { position: 'CAM', playerNumber: 28, playerName: 'Kim T (C)', xPct: 66, yPct: 42, role: 'Advanced Free 10 (Captain)' },
      { position: 'LW', playerNumber: 11, playerName: 'Romanelli B', xPct: 18, yPct: 24, role: 'Inside Forward' },
      { position: 'ST', playerNumber: 9, playerName: 'Rozo', xPct: 50, yPct: 16, role: 'Complete Forward' },
      { position: 'RW', playerNumber: 7, playerName: 'Xiao', xPct: 82, yPct: 24, role: 'Touchline Winger' }
    ]
  },
  '4-2-3-1': {
    id: '4-2-3-1',
    name: '4-2-3-1 Gegenpressing Double Pivot',
    description: 'Double pivot with #6 Lam and Captain #14 Mohiuddin shielding backline, liberating Captain #28 Tommy Kim to conduct rapid counter-attacks.',
    strengths: ['Unbreakable central transition defense', 'Explosive 4-man counter-attack waves'],
    vulnerabilities: ['Can leave striker isolated against 3-man backline'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: 'McKenzie', xPct: 50, yPct: 92, role: 'Sweeper Keeper' },
      { position: 'LB', playerNumber: 12, playerName: 'Eldessouky (C)', xPct: 16, yPct: 75, role: 'Fullback (Captain)' },
      { position: 'CB', playerNumber: 13, playerName: 'Tharney (C)', xPct: 38, yPct: 80, role: 'Center Back (Captain)' },
      { position: 'CB', playerNumber: 10, playerName: 'Wachtveitl', xPct: 62, yPct: 80, role: 'Center Back' },
      { position: 'RB', playerNumber: 17, playerName: 'Chen', xPct: 84, yPct: 75, role: 'Fullback' },
      { position: 'CDM', playerNumber: 6, playerName: 'Lam', xPct: 38, yPct: 60, role: 'Double Pivot Left' },
      { position: 'CDM', playerNumber: 14, playerName: 'Mohiuddin (C)', xPct: 62, yPct: 60, role: 'Double Pivot Right (Captain)' },
      { position: 'CAM', playerNumber: 28, playerName: 'Kim T (C)', xPct: 50, yPct: 38, role: 'Central Playmaker (Captain)' },
      { position: 'LW', playerNumber: 11, playerName: 'Romanelli B', xPct: 18, yPct: 26, role: 'Left Winger' },
      { position: 'ST', playerNumber: 9, playerName: 'Rozo', xPct: 50, yPct: 15, role: 'Striker' },
      { position: 'RW', playerNumber: 7, playerName: 'Xiao', xPct: 82, yPct: 26, role: 'Right Winger' }
    ]
  },
  '3-5-2': {
    id: '3-5-2',
    name: '3-5-2 Wing-Back Overload & Twin Strikers',
    description: 'Triple central defense with wingbacks providing width; twin strikers (#9 Rozo and #11 Romanelli) pin opposing center backs.',
    strengths: ['Complete midfield superiority (5v3)', 'Twin striker box presence'],
    vulnerabilities: ['Flanks exposed if wingbacks are caught high up'],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: 'McKenzie', xPct: 50, yPct: 92, role: 'Goalkeeper' },
      { position: 'CB', playerNumber: 5, playerName: 'Zeller', xPct: 28, yPct: 78, role: 'Left Center Back' },
      { position: 'CB', playerNumber: 10, playerName: 'Wachtveitl', xPct: 50, yPct: 80, role: 'Sweeper / Libero' },
      { position: 'CB', playerNumber: 13, playerName: 'Tharney (C)', xPct: 72, yPct: 78, role: 'Right Center Back (Captain)' },
      { position: 'LB', playerNumber: 12, playerName: 'Eldessouky (C)', xPct: 12, yPct: 52, role: 'Left Wing-Back (Captain)' },
      { position: 'CDM', playerNumber: 6, playerName: 'Lam', xPct: 50, yPct: 56, role: 'Central Midfielder' },
      { position: 'CM', playerNumber: 8, playerName: 'Bonchev', xPct: 34, yPct: 44, role: 'Central Midfielder' },
      { position: 'CAM', playerNumber: 28, playerName: 'Kim T (C)', xPct: 66, yPct: 44, role: 'Attacking Midfielder (Captain)' },
      { position: 'RB', playerNumber: 17, playerName: 'Chen', xPct: 88, yPct: 52, role: 'Right Wing-Back' },
      { position: 'ST', playerNumber: 9, playerName: 'Rozo', xPct: 38, yPct: 18, role: 'Target Striker' },
      { position: 'ST', playerNumber: 11, playerName: 'Romanelli B', xPct: 62, yPct: 18, role: 'Second Striker' }
    ]
  },
  '4-4-2': {
    id: '4-4-2',
    name: '4-4-2 Diamond Midfield (Peddie Primary System)',
    description: 'Classical 4-4-2 Diamond (4-1-2-1-2) with single-pivot anchor #6 Gabriel Lam, interior mezzalas #8 Owen Bonchev and Captain #14 Rayyaan Mohiuddin, and Captain #28 Tommy Kim pulling strings at the tip behind twin strikers #11 Blake Romanelli and #9 Brody Rozo.',
    strengths: [
      'Unmatched central midfield numerical dominance (4v3 / 4v2)',
      'Free playmaking conductor role for Captain Tommy Kim (#28)',
      'Overlapping flank corridors for Captain Noah Eldessouky (#12) and Nicholas Chen (#17)',
      'Twin dynamic strikers pinning and stretching opposition center backs'
    ],
    vulnerabilities: [
      'Demands high aerobic stamina from fullbacks to provide natural width',
      'Wide flank counter-attacks require LCM and RCM channel tracking'
    ],
    nodes: [
      { position: 'GK', playerNumber: 1, playerName: 'McKenzie', xPct: 50, yPct: 92, role: 'Sweeper Keeper' },
      { position: 'LB', playerNumber: 12, playerName: 'Eldessouky (C)', xPct: 16, yPct: 76, role: 'Attacking Left Fullback (Captain)' },
      { position: 'CB', playerNumber: 13, playerName: 'Tharney (C)', xPct: 38, yPct: 80, role: 'Stopper Center Back (Captain)' },
      { position: 'CB', playerNumber: 10, playerName: 'Wachtveitl', xPct: 62, yPct: 80, role: 'Covering Center Back' },
      { position: 'RB', playerNumber: 17, playerName: 'Chen', xPct: 84, yPct: 76, role: 'Right Fullback' },
      { position: 'CDM', playerNumber: 6, playerName: 'Lam', xPct: 50, yPct: 64, role: 'Diamond Base Anchor' },
      { position: 'CM', playerNumber: 8, playerName: 'Bonchev', xPct: 30, yPct: 48, role: 'Left Central Midfielder' },
      { position: 'CM', playerNumber: 14, playerName: 'Mohiuddin (C)', xPct: 70, yPct: 48, role: 'Right Central Midfielder (Captain)' },
      { position: 'CAM', playerNumber: 28, playerName: 'Kim T (C)', xPct: 50, yPct: 34, role: 'Diamond Tip Playmaker (Captain)' },
      { position: 'ST', playerNumber: 11, playerName: 'Romanelli B', xPct: 38, yPct: 16, role: 'Left Striker' },
      { position: 'ST', playerNumber: 9, playerName: 'Rozo', xPct: 62, yPct: 16, role: 'Right Striker' }
    ]
  }
};


export const MATCH_EVENTS_VEO_HAVERFORD: MatchEvent[] = [
  {
    "id": "veo-df91eca4",
    "minute": 7,
    "second": 15,
    "period": 1,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 28,
    "playerName": "Tommy Kim (C)",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/df91eca4-bd9b-4171-893d-6da93b295af0_1788317479.555815/video.mp4?v=7v9q8pPK",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/df91eca4-bd9b-4171-893d-6da93b295af0_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Counter Attack",
    "startX": 82,
    "startY": 26,
    "description": "Peddie transition counter: Captain Tommy Kim (#28) turns in pocket and fires from 22 yards. (Veo AI Period 1)"
  },
  {
    "id": "veo-86a673c2",
    "minute": 11,
    "second": 35,
    "period": 1,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 1,
    "playerName": "Dylan McKenzie",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/86a673c2-a2f7-495c-8282-739cfb12c034_1788317479.555815/video.mp4?v=0FOHwG9l",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/86a673c2-a2f7-495c-8282-739cfb12c034_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Dylan McKenzie (#1) athletic reaction save to deny Haverford shot attempt. (Veo AI Period 1)"
  },
  {
    "id": "veo-4c7c51a0",
    "minute": 13,
    "second": 8,
    "period": 1,
    "type": "Goal",
    "team": "Opponent",
    "playerNumber": 9,
    "playerName": "Haverford Fords",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/4c7c51a0-7704-4549-b0a2-991a39b54a3c_1788317479.555815/video.mp4?v=2Vr-NiPh",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/4c7c51a0-7704-4549-b0a2-991a39b54a3c_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.58,
    "success": true,
    "phase": "Counter Attack",
    "startX": 94,
    "startY": 34,
    "description": "Haverford Goal (Period 1, 13'): Vertical cutback into the penalty box finished into low corner. (Veo AI Official Clip)"
  },
  {
    "id": "veo-8b7d90a3",
    "minute": 16,
    "second": 15,
    "period": 1,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 28,
    "playerName": "Tommy Kim (C)",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/8b7d90a3-7840-4447-8fa8-89cf0aa8def2_1788317479.555815/video.mp4?v=D0hJ9wO1",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/8b7d90a3-7840-4447-8fa8-89cf0aa8def2_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Counter Attack",
    "startX": 82,
    "startY": 26,
    "description": "Peddie transition counter: Captain Tommy Kim (#28) turns in pocket and fires from 22 yards. (Veo AI Period 1)"
  },
  {
    "id": "veo-cded00c6",
    "minute": 19,
    "second": 41,
    "period": 1,
    "type": "Goal",
    "team": "Opponent",
    "playerNumber": 9,
    "playerName": "Haverford Fords",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/cded00c6-bb03-4a7d-ad64-bc747f764f62_1788317479.555815/video.mp4?v=gjk_1dSv",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/cded00c6-bb03-4a7d-ad64-bc747f764f62_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.58,
    "success": true,
    "phase": "Counter Attack",
    "startX": 94,
    "startY": 34,
    "description": "Haverford Goal (Period 1, 19'): Attacking sequence off right flank cross drilled into net before first intermission. (Veo AI Official Clip)"
  },
  {
    "id": "veo-f07ba327",
    "minute": 26,
    "second": 44,
    "period": 2,
    "type": "Shot",
    "team": "Opponent",
    "playerNumber": 11,
    "playerName": "Haverford Attack",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/f07ba327-7225-4d16-ab40-207b712e2705_1788317479.555815/video.mp4?v=2VxPy6iu",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/f07ba327-7225-4d16-ab40-207b712e2705_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Haverford shot attempt tested Peddie defensive block of Tharney and Wachtveitl. (Veo AI Period 2)"
  },
  {
    "id": "veo-3eabdafc",
    "minute": 29,
    "second": 15,
    "period": 2,
    "type": "Goal",
    "team": "Opponent",
    "playerNumber": 9,
    "playerName": "Haverford Fords",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/3eabdafc-f07f-47c1-8c0a-5913bb6e0015_1788317479.555815/video.mp4?v=YwaRAfam",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/3eabdafc-f07f-47c1-8c0a-5913bb6e0015_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.58,
    "success": true,
    "phase": "Counter Attack",
    "startX": 94,
    "startY": 34,
    "description": "Haverford Goal (Period 2, 29'): High turnover in final third leads to clinical strike inside right upright. (Veo AI Official Clip)"
  },
  {
    "id": "veo-fe533807",
    "minute": 29,
    "second": 15,
    "period": 2,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 1,
    "playerName": "Dylan McKenzie",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/fe533807-2f40-403c-b49a-8b528bc76a1e_1788317479.555815/video.mp4?v=2XbKbMD2",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/fe533807-2f40-403c-b49a-8b528bc76a1e_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Dylan McKenzie (#1) athletic reaction save to deny Haverford shot attempt. (Veo AI Period 2)"
  },
  {
    "id": "veo-06cc928b",
    "minute": 35,
    "second": 2,
    "period": 2,
    "type": "Shot",
    "team": "Opponent",
    "playerNumber": 11,
    "playerName": "Haverford Attack",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/06cc928b-6a11-40e9-85ae-01bf1d34dca8_1788317479.555815/video.mp4?v=00ys9FWU",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/06cc928b-6a11-40e9-85ae-01bf1d34dca8_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Haverford shot attempt tested Peddie defensive block of Tharney and Wachtveitl. (Veo AI Period 2)"
  },
  {
    "id": "veo-4c049e62",
    "minute": 41,
    "second": 52,
    "period": 2,
    "type": "Goal",
    "team": "Opponent",
    "playerNumber": 9,
    "playerName": "Haverford Fords",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/4c049e62-a5bf-418f-934d-74b1d09f43d9_1788317479.555815/video.mp4?v=Nhvja1fS",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/4c049e62-a5bf-418f-934d-74b1d09f43d9_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.58,
    "success": true,
    "phase": "Open Play",
    "startX": 94,
    "startY": 34,
    "description": "Haverford Goal (Period 2, 41'): Fast transition through half-space before second period whistle. (Veo AI Official Clip)"
  },
  {
    "id": "veo-c8ce0eb8",
    "minute": 41,
    "second": 52,
    "period": 2,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 1,
    "playerName": "Dylan McKenzie",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/c8ce0eb8-d651-4193-a476-ecc79ff6d247_1788317479.555815/video.mp4?v=iD5jIntY",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/c8ce0eb8-d651-4193-a476-ecc79ff6d247_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Dylan McKenzie (#1) athletic reaction save to deny Haverford shot attempt. (Veo AI Period 2)"
  },
  {
    "id": "veo-1c160071",
    "minute": 48,
    "second": 43,
    "period": 3,
    "type": "Shot",
    "team": "Opponent",
    "playerNumber": 11,
    "playerName": "Haverford Attack",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/1c160071-7c95-495f-9083-746380345b00_1788317479.555815/video.mp4?v=St2s4S9u",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/1c160071-7c95-495f-9083-746380345b00_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Haverford shot attempt tested Peddie defensive block of Tharney and Wachtveitl. (Veo AI Period 3)"
  },
  {
    "id": "veo-00d9a0b2",
    "minute": 59,
    "second": 43,
    "period": 3,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 28,
    "playerName": "Tommy Kim (C)",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/00d9a0b2-e89b-46f4-b02f-31c6981dce41_1788317479.555815/video.mp4?v=daL9_KhM",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/00d9a0b2-e89b-46f4-b02f-31c6981dce41_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Counter Attack",
    "startX": 82,
    "startY": 26,
    "description": "Peddie transition counter: Captain Tommy Kim (#28) turns in pocket and fires from 22 yards. (Veo AI Period 3)"
  },
  {
    "id": "veo-f7d5ec37",
    "minute": 66,
    "second": 32,
    "period": 3,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 1,
    "playerName": "Dylan McKenzie",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/f7d5ec37-6dc4-461e-843c-128f2e82c1df_1788317479.555815/video.mp4?v=OIMYNrKJ",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/f7d5ec37-6dc4-461e-843c-128f2e82c1df_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Dylan McKenzie (#1) athletic reaction save to deny Haverford shot attempt. (Veo AI Period 3)"
  },
  {
    "id": "veo-955497fe",
    "minute": 71,
    "second": 0,
    "period": 4,
    "type": "Shot",
    "team": "Opponent",
    "playerNumber": 11,
    "playerName": "Haverford Attack",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/955497fe-8896-48bf-aaf6-4d4a0418b6fa_1788317479.555815/video.mp4?v=VIt--J5f",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/955497fe-8896-48bf-aaf6-4d4a0418b6fa_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Haverford shot attempt tested Peddie defensive block of Tharney and Wachtveitl. (Veo AI Period 4)"
  },
  {
    "id": "veo-7c9d8fdf",
    "minute": 77,
    "second": 48,
    "period": 4,
    "type": "Goal",
    "team": "Opponent",
    "playerNumber": 9,
    "playerName": "Haverford Fords",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/7c9d8fdf-ab12-456e-854a-a3b685d7aa05_1788317479.555815/video.mp4?v=BXlEsn3q",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/7c9d8fdf-ab12-456e-854a-a3b685d7aa05_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.58,
    "success": true,
    "phase": "Open Play",
    "startX": 94,
    "startY": 34,
    "description": "Haverford Goal (Period 4, 77'): Late scramble in 18-yard box following saved initial attempt. (Veo AI Official Clip)"
  },
  {
    "id": "veo-2dc977f1",
    "minute": 84,
    "second": 20,
    "period": 4,
    "type": "Shot",
    "team": "Peddie",
    "playerNumber": 1,
    "playerName": "Dylan McKenzie",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/2dc977f1-451b-4319-8b7f-a350caa01420_1788317479.555815/video.mp4?v=QbeHPDVs",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/2dc977f1-451b-4319-8b7f-a350caa01420_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Dylan McKenzie (#1) athletic reaction save to deny Haverford shot attempt. (Veo AI Period 4)"
  },
  {
    "id": "veo-9d3f697d",
    "minute": 89,
    "second": 39,
    "period": 4,
    "type": "Shot",
    "team": "Opponent",
    "playerNumber": 11,
    "playerName": "Haverford Attack",
    "videoUrl": "https://c.veocdn.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/9d3f697d-cb02-498f-a233-a33ac5401369_1788317479.555815/video.mp4?v=et3VChnp",
    "thumbnailUrl": "https://veo-content-ii.s3.eu-west-1.amazonaws.com/3c6d8c4d-e123-49b3-9aec-61805299b2ba/highlight-v2/9d3f697d-cb02-498f-a233-a33ac5401369_1788317479.555815/thumbnail-854x480.jpg",
    "expectedGoals": 0.18,
    "success": false,
    "phase": "Open Play",
    "startX": 82,
    "startY": 26,
    "description": "Haverford shot attempt tested Peddie defensive block of Tharney and Wachtveitl. (Veo AI Period 4)"
  }
];

export const MATCH_EVENTS_LIVE_BLAIR: MatchEvent[] = [
  { id: 'ev-1', minute: 4, second: 12, team: 'Peddie', playerNumber: 8, playerName: 'Owen Bonchev', type: 'Pass', startX: 42, startY: 34, endX: 68, endY: 14, success: true, description: 'Diagonal 35m switch to Blake Romanelli on left wing', phase: 'Open Play' },
  { id: 'ev-2', minute: 7, second: 45, team: 'Peddie', playerNumber: 11, playerName: 'Blake Romanelli', type: 'Cross', startX: 88, startY: 12, endX: 98, endY: 32, success: false, description: 'Whip cross cleared by Blair CB', phase: 'Open Play' },
  { id: 'ev-3', minute: 12, second: 18, team: 'Opponent', playerNumber: 9, playerName: 'Blair Striker #9', type: 'Shot', startX: 84, startY: 28, expectedGoals: 0.08, success: false, description: 'Long distance shot deflected over bar', phase: 'Counter Attack' },
  { id: 'ev-4', minute: 18, second: 30, team: 'Peddie', playerNumber: 11, playerName: 'Blake Romanelli', type: 'Goal', startX: 92, startY: 22, expectedGoals: 0.42, success: true, description: 'GOAL! Blake Romanelli cuts inside on right foot and bends into top corner (1-0 Peddie)', phase: 'Open Play' },
  { id: 'ev-5', minute: 28, second: 10, team: 'Peddie', playerNumber: 10, playerName: 'Quinn Wachtveitl', type: 'Tackle', startX: 35, startY: 42, success: true, description: 'Standing tackle on Blair #10 to halt counter', phase: 'High Press' },
  { id: 'ev-6', minute: 34, second: 45, team: 'Peddie', playerNumber: 8, playerName: 'Owen Bonchev', type: 'Corner', startX: 105, startY: 0, endX: 96, endY: 32, success: true, description: 'Inswinging corner to near post', phase: 'Set Piece' },
  { id: 'ev-7', minute: 35, second: 0, team: 'Peddie', playerNumber: 10, playerName: 'Quinn Wachtveitl', type: 'Shot', startX: 96, startY: 32, expectedGoals: 0.38, success: false, description: 'Header glanced off crossbar', phase: 'Set Piece' },
  { id: 'ev-8', minute: 49, second: 22, team: 'Opponent', playerNumber: 11, playerName: 'Blair Winger #11', type: 'Goal', startX: 88, startY: 42, expectedGoals: 0.34, success: true, description: 'Goal for Blair on rebound scramble inside 6-yard box (1-1)', phase: 'Set Piece' },
  { id: 'ev-9', minute: 62, second: 15, team: 'Peddie', playerNumber: 6, playerName: 'Gabriel Lam', type: 'Interception', startX: 52, startY: 30, success: true, description: 'Stepped into passing lane to intercept clearance', phase: 'High Press' },
  { id: 'ev-10', minute: 73, second: 40, team: 'Peddie', playerNumber: 12, playerName: 'Noah Eldessouky', type: 'Key Pass', startX: 86, startY: 8, endX: 98, endY: 30, success: true, description: 'Low drilled cross across face of goal', phase: 'Open Play' },
  { id: 'ev-11', minute: 74, second: 0, team: 'Peddie', playerNumber: 28, playerName: 'Tommy Kim', type: 'Goal', startX: 98, startY: 30, expectedGoals: 0.65, success: true, description: 'GOAL! Tommy Kim clinical half-volley into side netting (2-1 Peddie!)', phase: 'Open Play' }
];

export const MAPL_SCOUTING_REPORTS: Record<string, ScoutingReport> = {
  'The Haverford School': {
    opponent: 'The Haverford School Fords',
    conference: 'Inter-Ac League (PA)',
    headCoach: 'Keith Cappo',
    formation: '4-3-3',
    keyPlaymakers: [
      '#9 Center Forward (clinical box finishing, 2 goals in Q1/Q2)',
      '#10 Central Midfield (direct passing vision and set-piece taker)',
      '#7 Right Winger (pace on overlap and early crosses)'
    ],
    tendencies: {
      buildup: 'Vertical direct switches into wide channels, rapid overloads in the penalty area.',
      defensiveBlock: 'Aggressive mid-to-high press; counter-press immediately upon turnovers.',
      vulnerabilityZone: 'Transitional channels behind high-pressing fullbacks when broken.',
      setPieceThreat: 'Whipped near-post corners and back-post cutbacks.'
    },
    recommendedTactics: [
      'Maintain compact 4-4-2 diamond central block to choke their interior central passing lanes.',
      'Utilize quick diagonal long releases from Tharney and Wachtveitl into Tommy Kim and Blake Romanelli channels.',
      'Double down on second-ball recoveries via Gabriel Lam (#6) and Rayyaan Mohiuddin (#14).'
    ],
    winProbabilityPct: 62.0
  },
  'Blair Academy': {
    opponent: 'Blair Academy Buccaneers',
    conference: 'MAPL',
    headCoach: 'Blair Coaching Staff',
    formation: '4-4-2',
    keyPlaymakers: ['#9 Target Striker (6\'3", aerial target)', '#10 Central Mid (primary set-piece taker)', '#11 Left Winger (speed in transition)'],
    tendencies: {
      buildup: 'Direct long balls from GK into striker chest; bypasses midfield play.',
      defensiveBlock: 'Low compact 4-4-2 block; rarely press above half field.',
      vulnerabilityZone: 'Half-spaces behind their wide midfielders when they push up on counter.',
      setPieceThreat: 'Long throw-ins directly into penalty area; near-post flicks.'
    },
    recommendedTactics: [
      'Overload their right flank with Eldessouky and Blake Romanelli to draw central defenders out.',
      'Deploy Gabriel Lam (#6) as second-ball sweeper against long goal kicks.',
      'Transition into compact 4-4-2 after 80th minute to protect lead.'
    ],
    winProbabilityPct: 78.5
  },
  'The Lawrenceville School': {
    opponent: 'The Lawrenceville School Big Red',
    conference: 'MAPL',
    headCoach: 'Lawrenceville Staff',
    formation: '4-3-3',
    keyPlaymakers: ['#8 Creative Pivot', '#7 Inverted Right Winger'],
    tendencies: {
      buildup: 'Short passing from back, high reliance on central midfielders turning under pressure.',
      defensiveBlock: 'Mid-block with aggressive fullback overlaps.',
      vulnerabilityZone: 'Spirited high line vulnerable to Tommy Kim runs behind.',
      setPieceThreat: 'Short corner routines to create 2v1 on edge of box.'
    },
    recommendedTactics: [
      'Trigger high press whenever backpass is made to their GK or right CB.',
      'Quick direct balls from Wachtveitl into Tommy Kim channel runs.'
    ],
    winProbabilityPct: 82.0
  },
  'The Hun School': {
    opponent: 'The Hun School Raiders',
    conference: 'MAPL',
    headCoach: 'Hun Staff',
    formation: '3-5-2',
    keyPlaymakers: ['#10 Striker (explosive acceleration)', '#5 Center Back'],
    tendencies: {
      buildup: 'Wingbacks stay very high; 3 center backs play wide.',
      defensiveBlock: 'Back 5 when defending deep.',
      vulnerabilityZone: 'Enormous space behind wingbacks on quick turnovers.',
      setPieceThreat: 'Tall center backs attacking far post.'
    },
    recommendedTactics: [
      'Isolate their outer center backs 1v1 with our wingers Xiao and Romanelli.',
      'Avoid crossing into crowded box of 3 tall CBs; utilize cutbacks to Sheinin at 18-yard arc.'
    ],
    winProbabilityPct: 74.0
  }
};

export const SIDELINE_SET_PIECE_PLAYBOOK = {
  attackingCorners: [
    {
      name: 'Falcon Claw (Near Post Overload)',
      triggerSignal: 'Left Hand Raised',
      taker: '#8 Owen Bonchev',
      description: 'Quinn Wachtveitl (#10) fakes far post then dashes across near post to flick on or head directly into near corner. Tommy Kim (#28) crashes 6-yard box for rebounds.',
      probabilityGoalPct: 28.5
    },
    {
      name: 'Gold Horizon (Far Post Deep Curl)',
      triggerSignal: 'Both Hands On Hips',
      taker: '#28 Tommy Kim',
      description: 'Outswinging curler to far post. Christian Tharney (#13) blocks goalkeeper sight line while Wachtveitl (#10) rises over fullback at back post.',
      probabilityGoalPct: 24.0
    },
    {
      name: 'Highstown Switch (Short Corner Triad)',
      triggerSignal: 'Taps Shinguard',
      taker: '#8 Owen Bonchev & #11 Blake Romanelli',
      description: 'Short pass to Romanelli, who lays back to Eldessouky (#12) arriving at top of box for first-time curling effort.',
      probabilityGoalPct: 21.0
    }
  ],
  defensiveCorners: [
    {
      name: 'Hybrid Zonal Anchor',
      organization: '5 Zonal Protectors + 3 Man-Markers + 1 Short Corner Disruptor + 1 Outlet Sprinter',
      anchor: '#10 Quinn Wachtveitl on 6-yard central zone',
      outlet: '#11 Blake Romanelli stationed at midfield stripe ready for counter sprint'
    }
  ],
  pressingTriggers: [
    {
      cue: 'Back-pass to Opponent Goalkeeper',
      action: 'Striker Rozo sprints at GK kicking foot; Wingers tuck inside to eliminate lateral fullback passes.'
    },
    {
      cue: 'Opponent Facing Own Goal under Pressure',
      action: 'All midfielders step up 10 yards to intercept panic clearance.'
    },
    {
      cue: 'Bouncing Ball or Heavy Touch on Sideline',
      action: 'Nearest fullback and winger double-team; trap ball against touchline.'
    }
  ],
  lateGameLockout: [
    {
      timeWindow: "80' - 90'+",
      formationShift: 'Shift from 4-3-3 to 4-4-2 Compact Low Block',
      rules: [
        'Zero risky passes through central midfield; play into corner flags.',
        'Keep 6 players strictly behind the ball at all times.',
        'All free kicks and throw-ins taken with maximum legal delay.',
        'Goalkeeper Dylan McKenzie holds ball for full allowed count before drop kick.'
      ]
    }
  ]
};
