import re

with open('prisma/seed.ts', 'r', encoding='utf-8') as f:
    seed_content = f.read()

# Exact player updates for seed.ts
# Player: (name, number, classYear, gradYear, pos, secPos, goals, assists, saves, notes)
# Bennett Cucchiara: 7, Freshman, M, G: 3, A: 3, P: 9
# Noah Eldessouky: 12, Senior, B, G: 0, A: 2, P: 2
# Tommy Kim: 28, Senior, F, G: 12, A: 4, P: 28
# Rayyaan Mohiuddin: 14, Junior, M, G: 1, A: 2, P: 4
# Michael Pratt: 9, Sophomore, F, G: 2, A: 3, P: 7
# Wyatt Raya: 2, Sophomore, M, G: 3, A: 1, P: 7
# Brody Rozo: 18, Sophomore, M, G: 0, A: 1, P: 1
# Jeet Sinha: 6, Junior, M, G: 1, A: 0, P: 2
# Christian Tharney: 13, Senior, M, G: 10, A: 5, P: 25
# Quinn Wachtveitl: 10, Senior, M, G: 2, A: 4, P: 8
# Carson Wiley: 22, Junior, B, G: 2, A: 1, P: 5
# Harry Xiao: 25, Junior, M, G: 1, A: 0, P: 2
# Jeffrey Zhang: 20, Junior, M, G: 0, A: 1, P: 1
# Dylan McKenzie: 98, Junior, G, Saves: 41, GP: 7
# Blake Romanelli: 26, Sophomore, M, Starting RM

new_peddie_players = """const PEDDIE_PLAYERS = [
  { externalId:'p-kim-t',       number:28, name:'Tommy Kim',           classYear:'Senior',    gradYear:2027, position:'ST',  secondaryPosition:'CAM', isCaptain:true,  squadLevel:'Varsity', tacticalRole:'Clinical Center-Forward & Transition Spearhead', scoutingTier:'NCAA D1 Collegiate Prospect', height:"5'11\"", weight:'168 lbs', hometown:'Princeton, NJ',       minutesPlayed:540, matchesPlayed:7, goals:12, assists:4, expectedGoals:11.45, expectedAssists:3.65, passCompletionPct:88.5, tackleSuccessPct:76.0, topSpeedMph:21.3, distanceCoveredMiles:45.8, shots:38, shotsOnTarget:28, keyPasses:18, interceptions:12, clearances:6, matchFormScore:9.6, photoUrl:'/media-day-headshots/IMG_000625.jpg', photoUrl2:'/media-day-previews/IMG_000632.jpg' },
  { externalId:'p-tharney',     number:13, name:'Christian Tharney',   classYear:'Senior',    gradYear:2027, position:'CDM', secondaryPosition:'CB',  isCaptain:true,  squadLevel:'Varsity', tacticalRole:'Single Pivot Regista & Set-Piece Commander', scoutingTier:'All-MAPL First Team Anchor', height:"6'1\"", weight:'176 lbs', hometown:'Kendall Park, NJ',   minutesPlayed:560, matchesPlayed:7, goals:10, assists:5, expectedGoals:8.85, expectedAssists:4.45, passCompletionPct:91.2, tackleSuccessPct:89.3, topSpeedMph:20.4, distanceCoveredMiles:48.5, shots:26, shotsOnTarget:18, keyPasses:22, interceptions:32, clearances:24, matchFormScore:9.5, photoUrl:'/media-day-headshots/IMG_000547.jpg', photoUrl2:'/media-day-previews/IMG_000560.jpg' },
  { externalId:'p-cucchiara',   number:7,  name:'Bennett Cucchiara',   classYear:'Freshman',  gradYear:2030, position:'LM',  secondaryPosition:'RM',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Starting Left Midfielder & Precision Set-Piece Specialist', scoutingTier:'Varsity Cornerstone Starter', height:"5'9\"", weight:'152 lbs', hometown:'Cranbury, NJ', minutesPlayed:480, matchesPlayed:7, goals:3, assists:3, expectedGoals:2.85, expectedAssists:3.10, passCompletionPct:88.2, tackleSuccessPct:78.0, topSpeedMph:21.0, distanceCoveredMiles:42.5, shots:16, shotsOnTarget:11, keyPasses:19, interceptions:16, clearances:8, matchFormScore:9.1, photoUrl:'/media-day-headshots/IMG_0001197.jpg', photoUrl2:'/media-day-previews/IMG_0001227.jpg' },
  { externalId:'p-romanelli',   number:26, name:'Blake Romanelli',     classYear:'Sophomore', gradYear:2029, position:'RM',  secondaryPosition:'RB',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Starting Right Midfielder & Blistering Sprinter (21.8 mph Peak)', scoutingTier:'Varsity Cornerstone Starter', height:"5'10\"", weight:'162 lbs', hometown:'Robbinsville, NJ', minutesPlayed:470, matchesPlayed:7, goals:0, assists:0, expectedGoals:0.60, expectedAssists:1.15, passCompletionPct:87.5, tackleSuccessPct:85.0, topSpeedMph:21.8, distanceCoveredMiles:44.2, shots:7, shotsOnTarget:3, keyPasses:12, interceptions:21, clearances:18, matchFormScore:8.8, photoUrl:'/media-day-headshots/IMG_000976.jpg', photoUrl2:'/media-day-previews/IMG_0001037.jpg' },
  { externalId:'p-wachtveitl',  number:10, name:'Quinn Wachtveitl',    classYear:'Senior',    gradYear:2027, position:'ST',  secondaryPosition:'CAM', isCaptain:false, squadLevel:'Varsity', tacticalRole:'Striker & Combination Attacking Threat', scoutingTier:'MAPL Emerging Talent', height:"5'10\"", weight:'160 lbs', hometown:'Princeton, NJ',       minutesPlayed:440, matchesPlayed:7, goals:2, assists:4, expectedGoals:2.40, expectedAssists:2.95, passCompletionPct:84.5, tackleSuccessPct:74.0, topSpeedMph:20.5, distanceCoveredMiles:38.0, shots:15, shotsOnTarget:9, keyPasses:14, interceptions:8, clearances:3, matchFormScore:8.7 },
  { externalId:'p-raya',        number:2,  name:'Wyatt Raya',          classYear:'Sophomore', gradYear:2029, position:'CM',  secondaryPosition:'RM',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Dynamic Attacking Midfielder & Clinical Finisher', scoutingTier:'Varsity Key Contributor', height:"5'9\"", weight:'154 lbs', hometown:'Princeton, NJ', minutesPlayed:390, matchesPlayed:7, goals:3, assists:1, expectedGoals:2.65, expectedAssists:1.40, passCompletionPct:86.4, tackleSuccessPct:78.5, topSpeedMph:20.6, distanceCoveredMiles:35.2, shots:14, shotsOnTarget:9, keyPasses:11, interceptions:10, clearances:4, matchFormScore:8.6 },
  { externalId:'p-pratt',       number:9,  name:'Michael Pratt',       classYear:'Sophomore', gradYear:2029, position:'ST',  secondaryPosition:'RW',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Direct Attacking Forward & Playmaker', scoutingTier:'Varsity Key Contributor', height:"5'10\"", weight:'160 lbs', hometown:'Pennington, NJ', minutesPlayed:380, matchesPlayed:7, goals:2, assists:3, expectedGoals:2.10, expectedAssists:2.45, passCompletionPct:85.2, tackleSuccessPct:72.0, topSpeedMph:20.9, distanceCoveredMiles:34.5, shots:12, shotsOnTarget:8, keyPasses:12, interceptions:7, clearances:2, matchFormScore:8.5 },
  { externalId:'p-wiley',       number:22, name:'Carson Wiley',        classYear:'Junior',    gradYear:2028, position:'CB',  secondaryPosition:'CDM', isCaptain:false, squadLevel:'Varsity', tacticalRole:'Ball-Playing Center-Back & Set-Piece Target', scoutingTier:'MAPL Defensive Core', height:"6'0\"", weight:'176 lbs', hometown:'Summit, NJ',         minutesPlayed:560, matchesPlayed:7, goals:2, assists:1, expectedGoals:1.45, expectedAssists:0.60, passCompletionPct:89.5, tackleSuccessPct:88.0, topSpeedMph:19.8, distanceCoveredMiles:44.5, shots:6, shotsOnTarget:4, keyPasses:5, interceptions:29, clearances:36, matchFormScore:9.0 },
  { externalId:'p-mohiuddin',   number:14, name:'Rayyaan Mohiuddin',   classYear:'Junior',    gradYear:2028, position:'CAM', secondaryPosition:'RM',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Central Advanced Playmaker (Tip of Diamond)', scoutingTier:'All-MAPL Playmaking Cornerstone', height:"5'9\"", weight:'157 lbs', hometown:'Hillsborough, NJ', minutesPlayed:500, matchesPlayed:7, goals:1, assists:2, expectedGoals:1.80, expectedAssists:2.60, passCompletionPct:88.0, tackleSuccessPct:78.0, topSpeedMph:21.1, distanceCoveredMiles:46.0, shots:14, shotsOnTarget:7, keyPasses:22, interceptions:18, clearances:4, matchFormScore:9.0 },
  { externalId:'p-eldessouky',  number:12, name:'Noah Eldessouky',     classYear:'Senior',    gradYear:2027, position:'LB',  secondaryPosition:'CB',  isCaptain:true,  squadLevel:'Varsity', tacticalRole:'Attacking Inverted Wing-Back & Engine', scoutingTier:'All-MAPL First Team Caliber', height:"5'10\"", weight:'160 lbs', hometown:'Monroe, NJ', minutesPlayed:560, matchesPlayed:7, goals:0, assists:2, expectedGoals:0.35, expectedAssists:2.40, passCompletionPct:89.0, tackleSuccessPct:86.5, topSpeedMph:21.1, distanceCoveredMiles:47.5, shots:7, shotsOnTarget:3, keyPasses:16, interceptions:24, clearances:21, matchFormScore:9.2, photoUrl:'/media-day-headshots/IMG_000493.jpg', photoUrl2:'/media-day-previews/IMG_000525.jpg' },
  { externalId:'p-sinha-jeet',  number:6,  name:'Jeet Sinha',          classYear:'Junior',    gradYear:2028, position:'CM',  secondaryPosition:'LM',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Central Midfielder & Possession Progressor', scoutingTier:'Varsity Core Contributor', height:"5'11\"", weight:'165 lbs', hometown:'Hightstown, NJ', minutesPlayed:460, matchesPlayed:7, goals:1, assists:0, expectedGoals:1.05, expectedAssists:1.10, passCompletionPct:91.8, tackleSuccessPct:89.5, topSpeedMph:20.9, distanceCoveredMiles:41.0, shots:11, shotsOnTarget:6, keyPasses:14, interceptions:21, clearances:12, matchFormScore:8.9, photoUrl:'/media-day-headshots/IMG_000761.jpg', photoUrl2:'/media-day-previews/IMG_000769.jpg' },
  { externalId:'p-xiao',        number:25, name:'Harry Xiao',          classYear:'Junior',    gradYear:2028, position:'RW',  secondaryPosition:'CM',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Wide Attacking Winger & Goal Threat', scoutingTier:'Varsity Rotation', height:"5'9\"", weight:'156 lbs', hometown:'Princeton, NJ', minutesPlayed:280, matchesPlayed:7, goals:1, assists:0, expectedGoals:0.90, expectedAssists:0.45, passCompletionPct:83.0, tackleSuccessPct:72.0, topSpeedMph:20.5, distanceCoveredMiles:24.0, shots:6, shotsOnTarget:3, keyPasses:7, interceptions:8, clearances:2, matchFormScore:8.1 },
  { externalId:'p-zhang-j',     number:20, name:'Jeffrey Zhang',       classYear:'Junior',    gradYear:2028, position:'ST',  secondaryPosition:'CAM', isCaptain:false, squadLevel:'Varsity', tacticalRole:'Second Striker & Tactical Combiner', scoutingTier:'Varsity Key Rotation', height:"5'10\"", weight:'163 lbs', hometown:'Short Hills, NJ', minutesPlayed:380, matchesPlayed:7, goals:0, assists:1, expectedGoals:1.10, expectedAssists:1.50, passCompletionPct:84.8, tackleSuccessPct:74.0, topSpeedMph:20.9, distanceCoveredMiles:33.0, shots:9, shotsOnTarget:4, keyPasses:9, interceptions:7, clearances:3, matchFormScore:8.4, photoUrl:'/media-day-headshots/IMG_000551.jpg', photoUrl2:'/media-day-previews/IMG_000558.jpg' },
  { externalId:'p-rozo',        number:18, name:'Brody Rozo',          classYear:'Sophomore', gradYear:2029, position:'CM',  secondaryPosition:'ST',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'High-Press Central Midfielder & Aerial Battler', scoutingTier:'Varsity Rotation', height:"5'10\"", weight:'162 lbs', hometown:'Robbinsville, NJ', minutesPlayed:270, matchesPlayed:7, goals:0, assists:1, expectedGoals:0.45, expectedAssists:0.80, passCompletionPct:84.0, tackleSuccessPct:80.0, topSpeedMph:20.4, distanceCoveredMiles:25.0, shots:5, shotsOnTarget:2, keyPasses:7, interceptions:11, clearances:5, matchFormScore:8.0 },
  { externalId:'p-mckenzie',    number:98, name:'Dylan McKenzie',      classYear:'Junior',    gradYear:2028, position:'GK',  secondaryPosition:undefined, isCaptain:false, squadLevel:'Varsity', tacticalRole:'Sweeper-Keeper & Shot-Stopper (41 Saves)', scoutingTier:'NCAA D1/D2 Goalkeeper Prospect', height:"6'2\"", weight:'184 lbs', hometown:'Plainsboro, NJ', minutesPlayed:560, matchesPlayed:7, goals:0, assists:0, expectedGoals:0, expectedAssists:0, passCompletionPct:89.5, tackleSuccessPct:0, topSpeedMph:17.8, distanceCoveredMiles:27.0, shots:0, shotsOnTarget:0, keyPasses:0, interceptions:6, clearances:18, saves:41, goalsConceded:12, cleanSheets:2, matchFormScore:9.2, photoUrl:'/media-day-headshots/IMG_000565.jpg' },
  { externalId:'p-bonchev',     number:8,  name:'Owen Bonchev',        classYear:'Sophomore', gradYear:2029, position:'CB',  secondaryPosition:'CDM', isCaptain:false, squadLevel:'Varsity', tacticalRole:'Ball-Playing Center-Back', scoutingTier:'Varsity Starter', height:"6'1\"", weight:'175 lbs', hometown:'Princeton, NJ', minutesPlayed:520, matchesPlayed:7, goals:0, assists:0, expectedGoals:0.15, expectedAssists:0.25, passCompletionPct:89.0, tackleSuccessPct:86.0, topSpeedMph:20.2, distanceCoveredMiles:41.0, shots:2, shotsOnTarget:1, keyPasses:4, interceptions:26, clearances:32, matchFormScore:8.8 },
  { externalId:'p-lam',         number:5,  name:'Gabriel Lam',          classYear:'Senior',    gradYear:2027, position:'RB',  secondaryPosition:'CB',  isCaptain:false, squadLevel:'Varsity', tacticalRole:'Starting Right Fullback', scoutingTier:'Varsity Starter', height:"5'10\"", weight:'164 lbs', hometown:'Princeton, NJ', minutesPlayed:530, matchesPlayed:7, goals:0, assists:0, expectedGoals:0.20, expectedAssists:0.75, passCompletionPct:91.2, tackleSuccessPct:87.5, topSpeedMph:20.8, distanceCoveredMiles:43.0, shots:3, shotsOnTarget:1, keyPasses:10, interceptions:23, clearances:24, matchFormScore:8.9 },
  // JV Players
  { externalId:'p-li-raymond',  number:31, name:'Raymond Li',          classYear:'Sophomore', gradYear:2029, position:'CM',  isCaptain:false, squadLevel:'JuniorVarsity', tacticalRole:'JV Central Midfielder', scoutingTier:'JV Development', height:"5'9\"", weight:'153 lbs', hometown:'Montgomery Township, NJ', minutesPlayed:0, matchesPlayed:0, goals:0, assists:0, expectedGoals:0, expectedAssists:0, passCompletionPct:0, tackleSuccessPct:0, topSpeedMph:0, distanceCoveredMiles:0 },
  { externalId:'p-kwok',        number:32, name:'Harrison Kwok',       classYear:'Sophomore', gradYear:2029, position:'CB',  isCaptain:false, squadLevel:'JuniorVarsity', tacticalRole:'JV Center-Back', scoutingTier:'JV Development', height:"5'11\"", weight:'165 lbs', hometown:'Edison, NJ',          minutesPlayed:0, matchesPlayed:0, goals:0, assists:0, expectedGoals:0, expectedAssists:0, passCompletionPct:0, tackleSuccessPct:0, topSpeedMph:0, distanceCoveredMiles:0 },
];"""

pattern = r"const PEDDIE_PLAYERS = \[[\s\S]*?\];"
seed_content = re.sub(pattern, new_peddie_players, seed_content)

with open('prisma/seed.ts', 'w', encoding='utf-8') as f:
    f.write(seed_content)

print("prisma/seed.ts updated successfully with real player stats!")
